- packages/api-explorer/__tests__/lib/oas-to-har.test.js
- packages/api-explorer/__tests__/lib/parse-response.test.js
- packages/api-explorer/src/lib/oas-to-har.js
- packages/api-explorer/src/lib/parse-response.js
This is to catch cases where they return `content-type: application/json` but do not return valid JSON
We have to clone the object first before we parse, as the objects can only be read once
> Add error handling around `await response.json()` call

- packages/api-explorer/__tests__/Example.test.jsx
- packages/api-explorer/src/Example.jsx
If example code language is JSON, it now renders with collapsible JSON viewer.
As shown with the example 200 response in [`examples.json`](https://readmeio.github.io/api-explorer/?selected=swagger-files%2Fexamples.json):
> Collapsible JSON viewer for example code

- packages/api-explorer/__tests__/Params.test.jsx
- packages/api-explorer/__tests__/fixtures/petstore/oas.json
- packages/api-explorer/src/form-components/SchemaField.jsx
- packages/syntax-highlighter/package-lock.json
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#fixed-fields-20
Can be tested here:
http://localhost:9966/?selected=swagger-files%2Fread-only.json
Here's the OAS file showing the hidden property:
> Make `readOnly` properties hidden in the form

- example/swagger-files/x-headers.json
- packages/api-explorer/__tests__/lib/oas-to-har.test.js
- packages/api-explorer/src/lib/oas-to-har.js
https://readme.readme.io/docs/swagger-extensions#section-static-headers
You can test it using: http://localhost:9966/?selected=swagger-files%2Fx-headers.json
> Add support for x-headers extension

- packages/api-explorer/src/AuthBox.jsx
This was really difficult to debug and I couldn't reproduce it but suspected
it was something to do with this <a> tag missing a href.
Greg figured it out yesterday that it was when you start on another page of ReadMe
then navigate to a reference page, this issue occurs.
I'm not 100% sure of the cause of the bug, i'm guessing it's something to do with
the pjax library highjacking all clicks on anchors, and because this is missing
an href, it gets highjacked instead of delegating to React.
I've demoed this working to Marc over slack.
> Fix issue with page refreshing on auth box open

- packages/api-explorer/__tests__/Params.test.jsx
- packages/api-explorer/package-lock.json
You can test this locally here: http://localhost:9966/?selected=swagger-files%2Ftypes.json
Search for "default value" and see that it is already in the code sample.
This issue luckily got fixed upstream:
https://github.com/mozilla-services/react-jsonschema-form/pull/1034
So to bring that in I needed to update my fork of the module.
I would love to get off of my fork and get back onto the main release,
but there's some outstanding work on my PR which means we can't right now:
https://github.com/mozilla-services/react-jsonschema-form/pull/954
> Fix issue where default values wouldn't be saved into the formData until edited

- packages/api-explorer/__tests__/lib/oas-to-har.test.js
- packages/api-explorer/src/lib/oas-to-har.js
On production right now if there's a nested object in a form, it always get
in the code sample even if the form values are not set:
```
--data '{"category":{}}'
```
This PR recursively removes empty objects from the form values so they
do not get set when making the request.
This problem was slightly exacerbated by #179 which auto applied default
values from the form to the samples.
> Fix problem where nested objects would appear empty

- packages/api-explorer/__tests__/lib/content-type-is-json.test.js
- packages/api-explorer/__tests__/lib/parse-response.test.js
- packages/api-explorer/src/Example.jsx
- packages/api-explorer/src/ResponseBody.jsx
- packages/api-explorer/src/lib/content-type-is-json.js
- packages/api-explorer/src/lib/parse-response.js
Resolves https://github.com/readmeio/api-explorer/issues/188.
Adds support for `Content-Type: application/vnd.api+json` as JSON, allowing [JSON APIs](https://jsonapi.org/) to render as one would expect.
> support json-api content type

- packages/api-explorer/__tests__/lib/Oas.test.js
- packages/api-explorer/__tests__/lib/oas-to-har.test.js
- packages/api-explorer/src/lib/Oas.js
- packages/api-explorer/src/lib/oas-to-har.js
Adds the following (with corresponding tests):
- Removes trailing slashes from the paths when operations are created
- Overrides Accept header types found in response definitions if an Accept header is sent in the form data
- Added a `$ref` lookup to path operation parameters
Asana tasks:
- https://app.asana.com/0/681252538274980/1108254356757915/f
- https://app.asana.com/0/681252538274980/977151049856241/f
> Remove trailing slashes from paths and header parameter improvements

- example/swagger-files/petstore.json
- example/swagger-files/types.json
- packages/api-explorer/__tests__/Params.test.jsx
- packages/api-explorer/__tests__/fixtures/petstore/oas.json
- packages/api-explorer/src/form-components/SchemaField.jsx
> strip out the string format that we do not support.

- packages/api-explorer/src/Doc.jsx
- packages/api-explorer/src/block-types/Content.jsx
- packages/api-explorer/src/block-types/TextArea.jsx
- packages/api-explorer/src/index.jsx
- packages/markdown/__tests__/__snapshots__/index.test.js.snap
- packages/markdown/__tests__/index.test.js
- packages/markdown/components/Anchor.jsx
- packages/markdown/contexts/BaseUrl.js
- packages/markdown/index.js
Create baseUrl [context](https://reactjs.org/docs/context.html) and revert prop passing in #176.
`baseUrl` isn't properly being passed down for certain fields such as parameter descriptions, excerpts, and tables. Taking advantage of contexts should eliminate the need for all the props passing that was being done.
> Improve handling of baseUrl

- example/swagger-files/auth-types.json
- packages/api-explorer/__tests__/lib/get-auth.test.js
- packages/api-explorer/src/lib/get-auth.js
Bearer authentication is just a regular API key:
https://swagger.io/docs/specification/authentication/bearer-authentication/
But it comes through like this:
```
{
type: 'http',
scheme: 'bearer'
}
```
Which `getAuth()` incorrectly picked up as though it should be HTTP auth.
This adds support for bearer to `getAuth()`
> Add support for bearer auth

- packages/api-explorer/__tests__/Params.test.jsx
- packages/api-explorer/src/form-components/SchemaField.jsx
This caused some formats to get removed, which meant that for integers
we were setting the default `int32` instead of `int64`.
We did have tests for this, but because the module was mutating the data
we were testing against the broken schema!
https://github.com/readmeio/api-explorer/pull/202
> Fix regression introduced in #202

- example/swagger-files/parameters-with-refs.json
- example/swagger-files/types.json
- packages/api-explorer/__tests__/lib/parameters-to-json-schema.test.js
- packages/api-explorer/src/lib/parameters-to-json-schema.js
This fixes a bug in our handling of parameters with child `$ref` pointers where we'd fail to resolve those linked definitions, and ultimately fail out while rendering the resource with an error that looked like the following:
I also added a few more test cases into our `types.json` example schema for `$ref` accessors.
> Adding support for parameters that may have child `$ref` pointers.

- example/reference/index.html
- example/reference/src/Preview.jsx
- example/src/ApiList.jsx
- example/src/SpecFetcher.jsx
- example/swagger-files/petstore.json
This introduces a few minor redesigns to our https://preview.readme.io/reference/ page and introduces:
* A loading state.
* Handling error states a little differently and removing the "Like what you see?" box if errors are present.
Old:
Refreshed:
> Redesigning the error and loading states in the reference demo

- example/swagger-files/types.json
- packages/api-explorer/api-explorer.css
> Fix style issue when "array of objects" contains another object

- packages/api-explorer/__tests__/Doc.test.jsx
- packages/api-explorer/src/Doc.jsx
- packages/api-explorer/src/lib/get-path-operation.js
Resolves a bug where projects load pages that are synced from a spec file in addition to pages that are manually added.
> 🐛 manual endpoints may not have a URL specified in the OAS spec

- example/swagger-files/additional-properties.json
- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
This incorporates a branch on our existing [react-jsonschema-form](https://github.com/mozilla-services/react-jsonschema-form) fork (now moved to our @readmeio org), to add support for `$ref` pointers on `additionalProperties` entries in data models.
Previously, if there was no `type` detected within `additionalProperties`, react-jsonschema-form would attempt to guess the type of the object as a `string`. Now, if a `$ref` pointer is present, it will be loaded as expected.
See https://github.com/readmeio/react-jsonschema-form/pull/1 for the full changeset of that fix and https://github.com/readmeio/react-jsonschema-form/pull/2 for the full changeset of what we're running in this (temporary) react-jsonschema-form fork.
> Adding support for $ref pointers to additionalProperties

- packages/api-explorer/src/lib/get-path.js
this is covering the case where an invalid apisetting is being passed.
> 🐛 we need to check if swagger.paths exists

- example/swagger-files/types.json
- packages/api-explorer/__tests__/Params.test.jsx
- packages/api-explorer/api-explorer.css
- packages/api-explorer/package-lock.json
- packages/api-explorer/src/Params.jsx
- packages/api-explorer/src/form-components/SchemaField.jsx
We have a current problem in the explorer with our integer `format` support where we're misidentifying `uint64` as `int32`. This resolves that, as well as expands our support to the following integer formats:
* `int8`
* `uint8`
* `int16`
* `uint16`
* `uint32`
* `uint64`
Ideally, we wouldn't need to hardcode these kinds of things in here, but the [TSC is working through some proposals](https://github.com/OAI/OpenAPI-Specification/issues/845) on a format registry to the spec.
> Expanding our support for integer formats to a wider variety.

- packages/api-explorer/src/ResponseSchema.jsx
Response schema descriptions that contain Markdown are not having that Markdown parsed, resulting in improperly formatted content such as the following:
```
"responses": {
"403": {
"description": "No access_token was provided with this request. \n \n The access_token provided is not permitted to access the specified resource. \r \r Person not found",
"content": {
"application/json": {
"schema": {
"$ref": "#/components/schemas/RestException"
}
}
}
},
```
And parsed as Markdown:
> Pass response schema descriptions through the Markdown parser

- example/swagger-files/response-schemas.json
- packages/api-explorer/__tests__/Example.test.jsx
- packages/api-explorer/__tests__/fixtures/string/oas.json
- packages/api-explorer/src/Example.jsx
| [🎟 Asana](https://app.asana.com/0/681252538274980/1130342849794131/f) |
| :--- |
This adds in some protections on our JSON rendering in response examples to prevent us from failing out on "Unexpected token" errors if we're attempt to render a string as JSON that isn't actually JSON. This kind of thing can happen if a response is documented as returning JSON, but instead has a simple string documented as an example.
> If we fail to render JSON, fallback to string rendering.

- example/swagger-files/additional-properties.json
- packages/api-explorer/package-lock.json
This updates our [react-jsonschema-form](https://github.com/readmeio/react-jsonschema-form) fork to the latest HEAD of our [`dist-committed`](https://github.com/readmeio/react-jsonschema-form/tree/dist-committed) branch.
Fixes that are included in this changeset are the following:
* Preventing data loss on `additionalProperties` key changes. https://github.com/readmeio/react-jsonschema-form/pull/3
* Since I opted to not write tests on this in the library, instead doing manual testing, the way you can test this is to:
1. Load http://localhost:9966/?selected=swagger-files%2Fadditional-properties.json
2. Click on the "object with 'additionalProperties: { type: object, properties: ... }' and custom title"  parameter.
3. Add a new entry. 
4. In the `newKey` input box, type in a new value.
5. …
> Updating our react-jsonschema-form fork to the latest HEAD.

- packages/api-logs/package-lock.json
- packages/api-logs/package.json
Reverts readmeio/api-explorer#264
Upgrading to this version has broken the local dev server.
```
ERROR in ./packages/api-logs/node_modules/react-visibility-sensor/dist/visibility-sensor.js
Module not found: Error: Can't resolve 'ReactDOM' in '/Users/jon/code/readmeio/api-explorer/packages/api-logs/node_modules/react-visibility-sensor/dist'
@ ./packages/api-logs/node_modules/react-visibility-sensor/dist/visibility-sensor.js 4:286-324
@ ./packages/api-logs/index.jsx
@ ./example/src/Demo.jsx
@ ./example/index.jsx
```
> Revert "Bump react-visibility-sensor from 4.1.3 to 5.1.1"

- packages/api-explorer/src/block-types/Code.jsx
This fixes an issue when navigating to /reference on a project
and switching code tabs, which makes the page do a full refresh.
No idea why, lets see if this fixes it on a PR app.
> Add href attribute to <a> tags used for switching code tabs

- packages/api-logs/__tests__/index.test.jsx
- packages/api-logs/index.jsx
Asana Link: https://app.asana.com/0/681252538274980/1129600570638092/f
When splitReference was enabled, the relative links in the api-logs component were causing 404s, since we were treating /reference as a child project, when we should have been using just the api endpoint.
baseUrl that gets to the api-logs component never has a trailing slash, so we should account for that.
> Fix logs in the hubs with split reference

- packages/api-explorer/__tests__/ResponseSchema.test.jsx
- packages/api-explorer/src/ResponseSchema.jsx
This resolves a persistent error on every usage of the Explorer where because we render response descriptions as Markdown, we're nesting a `<p>` tag within another `<p>` tag, which is invalid DOM.
```
Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.
in p
in p
in div
in div
in ResponseSchema
in div
in div
in div
in EndpointErrorBoundary
in div
in Doc
in div
in div
in ApiExplorer
in ErrorBoundary
in Unknown (created by Demo)
in div (created by Demo)
in Demo (created by _class)
in _class
in AppContainer
```
> fix: Stop nesting Markdown response descriptions in a p tag

- packages/markdown/__tests__/__snapshots__/index.test.js.snap
- packages/markdown/__tests__/index.test.js
- packages/markdown/components/Anchor.jsx
Writing a link with a `[target]` attribute should render, well... a link with a `[target]` attribute, obviously...
> Set link tag's [target] in the editor

- package-lock.json
- package.json
- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/api-explorer/webpack.config.js
- packages/api-logs/README.md
- packages/api-logs/package-lock.json
- packages/api-logs/package.json
- packages/api-logs/webpack.config.js
- packages/oas-extensions/package-lock.json
- packages/oas-extensions/package.json
- webpack.config.js
- webpack.prod.js
This upgrades all packages to Webpack 4 and removes a handful of packages that are not being used.
```
Time: 31348ms
Asset     Size  Chunks                    Chunk Names
./example/demo-bundle.js  6.59 MB       0  [emitted]  [big]  demo
./example/reference-bundle.js  6.39 MB       1  [emitted]  [big]  reference
./example/demo-bundle.js.map  7.12 MB       0  [emitted]         demo
./example/reference-bundle.js.map  6.92 MB       1  [emitted]         reference
```
```
$ du -hs packages/*/dist
1.5M	packages/api-explorer/dist
156K	packages/api-logs/dist
```
```
Time: 29296ms
Asset      Size     Chunks             Chunk Names
demo-bundle.js  6.56 MiB       demo  [emitted]  demo
demo-bundle.js.map  6.37 MiB       demo  [emitted]  demo
reference-bundle.js  6.39 MiB  reference  [emitted] …
```
> feat: Upgrade to Webpack 4

- packages/api-explorer/__tests__/lib/upgrade-legacy-responses.test.js
- packages/api-explorer/package.json
- packages/api-explorer/src/EndpointErrorBoundary.jsx
- packages/api-explorer/src/ErrorBoundary.jsx
- packages/api-explorer/src/ResponseExample.jsx
- packages/api-explorer/src/lib/upgrade-legacy-responses.js
When we shipped https://github.com/readmeio/api-explorer/pull/312 two weeks ago, it inadverantly broke all APIs that were manually documented through our manual editor because those APIs have their languages (media types) as a `language` property, but we're now building up (via the code shower utility) a `languages` array.
Since the explorer now expects `languages` to be present, all manually documented APIs were crashing.
Since changing the shape of this data would require a large database migration, and we're currently in the process of redoing our manual editor to be OAS first (which will the code shower utility already handles), I've decided to write some adhoc code to upgrade these response examples on the fly to the new, expected, format.
> fix: Backport support for multi media types to legacy Manual APIs

- example/swagger-files/types.json
- packages/api-explorer/__tests__/Params.test.jsx
- packages/api-explorer/src/form-components/SchemaField.jsx
This will resolve issues where if a customer documents a parameter as "mixed type" in our manual editor, we'll no longer error when rendering that parameter as "mixed type" isn't a valid OAS type.
See https://docs.robinpowered.com/reference#get-organization for a production example of this currently failing.
> If we encounter "mixed type" as a type, convert it to "string"

- packages/api-explorer/src/ResponseExample.jsx
|🎟 [Asana](https://app.asana.com/0/681252538274980/1147390971548626/f)|
|:--:|
Endpoints with duplicate examples of the same response code _and_ language type would not  show in the explorer. I fixed this by adding a check for `multipleExamples` entry in the `hasExamples` logic:
https://github.com/readmeio/api-explorer/blob/087219de968bd1e8487411af8510d59fd1d8e12b/packages/api-explorer/src/ResponseExample.jsx#L175-L177
> Fix Multi-Example Display Logic

- example/swagger-files/examples.json
- packages/api-explorer/__tests__/ExampleTabs.test.jsx
- packages/api-explorer/__tests__/ResponseSchema.test.jsx
- packages/api-explorer/__tests__/ResponseTabs.test.jsx
- packages/api-explorer/__tests__/fixtures/example-results/oas.json
- packages/api-explorer/__tests__/lib/create-code-shower.test.js
- packages/api-explorer/package.json
- packages/api-explorer/src/ResponseExample.jsx
- packages/api-explorer/src/ResponseSchema.jsx
- packages/api-explorer/src/ResponseTabs.jsx
- packages/api-explorer/src/lib/create-code-shower.js
When a response is stored within a `$ref` component, the explorer wouldn't display it in response tab window, and the description (if present) would be missing from the response schema body box.
With this fix in place, `$ref` responses appear as they would if they weren't loaded as a component:
> Fix issue where responses stored as a $ref wouldn't be fully loaded

- packages/api-explorer/style/main.scss
Fixes this issue by wrapping the `:before` pseudo with a `body.hub-full` to limit it to pages using the API reference layout:
<p align=center>
> Fix API Righthand Sidebar Showing on Guides Pages

- packages/api-explorer/__tests__/Params.test.jsx
- packages/api-explorer/src/form-components/SchemaField.jsx
This resolves a regression of functional on schemas with `additionalProperties` no longer having editable labels/keys.
*Note:* Keys don't update until you focus out of the input, but this is the same behavior that RJSF has currently https://rjsf-team.github.io/react-jsonschema-form/
> Fixing a regression of additionalProperties keys not being editable

- packages/api-logs/__tests__/fixtures/requestmodel.json
- packages/api-logs/__tests__/index.test.jsx
- packages/api-logs/index.jsx
Similar to these PRs:
- https://github.com/readmeio/readme/pull/2140
- https://github.com/readmeio/readme-metrics-api/pull/147
> ♻️ refer to new pointers for log

- packages/api-explorer/style/main.scss
|🎟 [Asana](https://app.asana.com/0/681252538274980/1153860678793593/f)|
|:--:|
Some key/value fields do not align very well when nested. 
**Broken**: go to [this example page](https://stackpath.dev/reference/workloads#updateworkload) and scroll down to Annotations (nested under Metadata) and click the Add button to create a new set of key/value pairs.
> Align Key/Val Param Fields

- packages/api-logs/index.jsx
From this thread: https://readmeio.slack.com/archives/CRE57G3J7/p1579654198009000
Fixes the logs URL. See here for another reference: https://github.com/readmeio/api-explorer/blob/master/packages/api-logs/index.jsx#L228
We currently have a temporary fix via redirects in the parent project settings
> 🐛 fix broken api log url

- packages/api-explorer/__tests__/ResponseSchemaBody.test.jsx
- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/api-explorer/src/ResponseSchemaBody.jsx
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
This updates the [oas](https://www.npmjs.com/package/oas) package to do a few things:
- Move core OAS-specific work from `ResponseSchemaBody` out of that and into the `oas` package.
- Fix a bug in that code where if we encountered a response schema property, or `$ref`, that didn't have an explicit `type` property set, we wouldn't include it in the flattened output.
This PR doesn't add any unit tests because those tests have been added in the oas package instead. See https://github.com/readmeio/oas/pull/104 for the PR that has this code migration, bug fix, and unit tests.
That said, here is a screenshot of the schema bug in action:
And with the fix:
See https://github.com/readmeio/oas/pull/104/files#diff-50da53e033459b1db3c580ac63f65edfR73-R88 for the full test case.
> fix: updating the oas package to pull in some fixes for handling response schemas

- packages/oas-to-har/__tests__/fixtures/common-parameters.json
- packages/oas-to-har/__tests__/index.test.js
- packages/oas-to-har/src/index.js
This resolves a bug in the `oas-to-har` package where because it didn't support common parameters, any form input that belonged to one would be ignored and not added to code samples in the explorer.
> fix: oas-to-har now supports common parameters

- packages/api-explorer/__tests__/fixtures/parameters/common.json
- packages/api-explorer/__tests__/index.test.jsx
- packages/api-explorer/src/index.jsx
- packages/oas-to-har/__tests__/index.test.js
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
- packages/oas-to-har/src/index.js
This resolves a major bug in the `oas-to-har` package with regard to how we were handling common parameters. 
When we call the the package to create a HAR object to call, we'd supply it with a `pathOperation` object that represented the current path+method we're processing in the current OAS file. The problem is that inside `oas-to-har`, when constructing parameters to add into the HAR, we were doing so on the `pathOperation` object that was supplied instead of against an instance variable to that function.
This meant that every time a user would click "Try It" to make an API call, we'd re-add the same common parameters to the instanced `operation` variable further up the stack in `Doc.jsx`. This would then cascade back down into `oas-to-har` and we'd slowly begin to exponentially double …
> fix: stop mutating the supplied pathOperation object in oas-to-har

- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/api-explorer/src/Doc.jsx
I'm iffy on the header name, but this will allow people to split apart "Try It" requests in their Developer Metrics.
> feat: setting a custom header for all "Try It" requests

- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/api-explorer/src/Doc.jsx
There's a bug in Firefox and Chrome where they don't respect setting a custom User-Agent on fetch() requests, so instead to let API metrics know that this request came from the Explorer, we're setting a vendor header instead.
https://stackoverflow.com/questions/42815087/sending-a-custom-user-agent-string-along-with-my-headers-fetch
Also updated `fetch-har` to 2.2.1 so it uses the `Headers` API instead of working with a bare object in the `Request` module.
> fix: setting `x-readme-api-explorer` instead of a custom UA

- example/swagger-files/examples.json
- packages/api-explorer/__tests__/ResponseExample.test.jsx
- packages/api-explorer/src/ResponseExample.jsx
This resolves a bug in the explorer's handling of legacy manual API entered, multi-example non-JSON responses, which just so happens to also be a bug that's preventing some customers from being able to upgrade off our legacy API Explorer.
What was happening was that we were failing to catch JSON parsing errors on non-JSON (or invalid JSON) content in [react-json-view](https://www.npmjs.com/package/react-json-view) and instead supplying the example to our [syntax-highlighter](https://www.npmjs.com/package/@readme/syntax-highlighter) like we do for singular examples.
In this PR, I've also slightly tweaked the copy on the dropdown label from "Set an example" to "Choose an example" as I feel that makes more sense.
> Support for legacy manual API multi-example, non-JSON responses

- packages/oas-to-har/__tests__/index.test.js
- packages/oas-to-har/src/index.js
This resolves an edge case where if an `x-headers` array, or as a parameter, with a `Content-Type` is present on an OAS, we'd double up `Content-Type` when building a HAR with the mime type defined on the `requestBody`.
Content types defined in `x-headers`, or parameters, should always take precedence.
> fix: edge case where Content-Type could sometimes be doubled up

- packages/api-explorer/src/Doc.jsx
We don't always have logs, so there's a ton of gray area just hangin' out above the parameters. We also update code snippets when you type, but you can't see it when the params are so far down!
> Put params before logs

- example/swagger-files/types.json
- packages/api-explorer/__tests__/Params.test.jsx
- packages/api-explorer/src/Params.jsx
- packages/api-explorer/src/ResponseExample.jsx
There appears to be a bug in RJSF right now where it's disabling input into `<input type="datetime-local">` inputs in Firefox. As a quick hotfix, we're downgrading our format support of `datetime` and `date-time` to simple text inputs.
> fix: downgrading datetime inputs to simple text inputs

- example/swagger-files/empty-params.json
- package.json
- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
This upgrades our core `@readme/oas-tooling` package to resolve a bug where we'd allow empty `default` properties through on parameters and request bodies, without first looking for `allowEmptyValue`. The downstream effect of this was that we were happily passing along empty defaults when they shouldn't be present, resulting in API requests being made with payloads that looked as such:
Check https://github.com/readmeio/oas/pull/110 for more details, and comprehensive unit tests, on the fix.
I've added a new `empty-params` document into our examples directory to showcase this error (and fix) in action.
> chore(deps): upgrading @readme/oas-tooling to 2.1.0

- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
This updates @readme/oas-tooling to 2.1.1 to resolve an issue with the `parameters-to-json-schema` library we're using where it would error on parsing OpenAPI schemas with a `null` property.
See https://github.com/readmeio/oas/pull/114 for the full details.
> chore(deps): upgrading @readme/oas-tooling to 2.1.1

- packages/api-explorer/__tests__/Doc.test.jsx
- packages/api-explorer/__tests__/index.test.jsx
- packages/api-explorer/src/Doc.jsx
- packages/api-explorer/src/index.jsx
Rendering workaround for anchor tags. Temporarily rendering h1 tags until components have a chance to lazy load.
https://app.asana.com/0/1163123796550394/1117151359430917
> fix: h1 anchor rendering

- packages/markdown/__tests__/__snapshots__/magic-block-parser.test.js.snap
- packages/markdown/__tests__/magic-block-parser.test.js
- packages/markdown/components/Embed.jsx
- packages/markdown/processor/parse/magic-block-parser.js
- packages/markdown/processor/parse/variable-parser.js
> fix(markdown@v5): fix magic block null cases.

- example/swagger-files/types.json
- packages/api-explorer/__tests__/Params.test.jsx
- packages/api-explorer/__tests__/__fixtures__/string/oas.json
- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
The `parameters-to-json-schema` library in [@readme/oas-tooling](https://www.npmjs.com/package/@readme/oas-tooling) will now convert `minLength` and `maxLength` into the JSON Schema `minimum` and `maximum` counterparts.
> chore(deps): upgrading @readme/oas-tooling to 3.1.0 for min/max support

- packages/markdown/package.json
- packages/markdown/webpack.config.js
- packages/syntax-highlighter/codemirror.jsx
We needed to be able to pull in the @readme/markdown package into the core application from the server-side code. These changes allow us to do this.
To see the current behavior: https://npm.runkit.com/%40readme%2Fmarkdown
> ✨ implement isomorphic markdown parser package

- package-lock.json
- package.json
Reverts readmeio/api-explorer#533. This is breaking dist builds in the explorer with the following errors:
```
ERROR in /Users/jon/code/readmeio/api-explorer/node_modules/css-loader/dist/cjs.js!/Users/jon/code/readmeio/api-explorer/node_modules/sass-loader/dist/cjs.js!./styles/main.scss
Module build failed: TypeError: this.getResolve is not a function
at Object.loader (/Users/jon/code/readmeio/api-explorer/node_modules/sass-loader/dist/index.js:52:26)
@ ./styles/main.scss 3:14-129
@ ./index.js
@ multi ./index.js
ERROR in /Users/jon/code/readmeio/api-explorer/node_modules/css-loader/dist/cjs.js!/Users/jon/code/readmeio/api-explorer/node_modules/sass-loader/dist/cjs.js!./components/Heading/style.scss
Module build failed: TypeError: this.getResolve is not a function
at Object.loader …
```
> revert: "chore(deps-dev): Bump sass-loader from 7.3.1 to 8.0.2"

- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/api-explorer/src/ErrorBoundary.jsx
- packages/api-explorer/src/Params.jsx
- packages/api-explorer/src/form-components/UnsupportedField.jsx
I added support for being able to override `UnsupportedField` in https://github.com/readmeio/react-jsonschema-form/pull/10. Without this, we had no way to capture errors from RJSF.
> fix: creating a custom UnsupportedField for RJSF to handle errors

- example/swagger-files/types.json
- packages/api-explorer/__tests__/Doc.test.jsx
- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/api-explorer/src/ErrorBoundary.jsx
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
This upgrades `@readme/oas-tooling` to v3.1.2 to resolve a bug we had in our parameter to JSON Schema code where it would fail on freeform objects that had `additionalProperties` instead of `properties`.
See https://github.com/readmeio/oas/pull/130 for the full fix.
> chore(deps): upgrading @readme/oas-tooling to 3.1.2

- packages/api-explorer/package-lock.json
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
This fixes two issues with how we render JSON Schema:
- fix: magically resolving objects that are typod as arrays [`#132`](https://github.com/readmeio/oas/pull/132)
- fix: don't prepare a parameter/body schema if it's empty [`#131`](https://github.com/readmeio/oas/pull/131)
> fix: updating @readme/oas-tooling to 3.1.3

- packages/api-explorer/__tests__/Params.test.jsx
- packages/api-explorer/src/Params.jsx
This will fix the following console warning that crops up on every Explorer with multiple types of parameters on a single operation:
> fix: setting a unique idPrefix for all forms to prevent dupe DOM IDs

- .prettierrc
- package-lock.json
- package.json
- packages/api-explorer/.prettierrc
- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/api-logs/.prettierrc
- packages/api-logs/package-lock.json
- packages/api-logs/package.json
- packages/http-status-codes/.prettierrc
- packages/http-status-codes/package-lock.json
- packages/http-status-codes/package.json
- packages/markdown-magic/.prettierrc
- packages/markdown-magic/package-lock.json
- packages/markdown-magic/package.json
- packages/markdown/.prettierrc
- packages/markdown/package-lock.json
- packages/markdown/package.json
- packages/markdown/processor/compile/code-tabs.js
- packages/oas-to-har/.prettierrc
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
- packages/oas-to-har/src/index.js
- packages/syntax-highlighter/.prettierrc
- packages/syntax-highlighter/package-lock.json
- packages/syntax-highlighter/package.json
- packages/variable/.prettierrc
- packages/variable/package-lock.json
- packages/variable/package.json
This upgrades `@readme/eslint-config` to 2.0.0 which allows us to start pulling in our shared Prettier config.
> chore(deps-dev): upgrading @readme/eslint-config to 2.0.0

- packages/api-explorer/src/index.jsx
This resolves a bug in our Markdown processing of links where we weren't prepending the supplied `baseUrl` because, when the old Markdown processor was enabled, we were loading a context consumer that was never actually set up.
What happens now is that if the new Markdown engine is enabled, we'll use the context for `BaseUrl` and `GlossaryTerms` from `@readme/markdown`, otherwise we'll use the same files but from `@readme/markdown-engine`.
> fix: using the appropriate markdown contexts when necessary

- packages/markdown/index.js
Describe in detail what this PR is for.
We are not leveraging the `normalize` function in the other consumable methods in the markdown repository. This PR opens that up so it is an option by default.
Provide as much information as you can on how to test what you've done.
> 🐛 create normalize as an option

- example/swagger-files/types.json
- packages/api-explorer/package-lock.json
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
This updates our `@readme/oas-tooling` and `@readme/react-jsonschema-form` dependencies to resolve a couple issues with malformed `array` schemas:
* If an `array` schema did not have an `items` property, we would fail to render the operation.
* If an `array` schema had an `items` property that evaluated to `{}`, we would fail to render the operation.
What will happen now is if we encounter one of these malformed schemas where `items` is missing, we'll repair it and add `items: {}` so that the array can be utilized as a standard mixed-data input.
See https://github.com/readmeio/oas/pull/138 and https://github.com/readmeio/react-jsonschema-form/pull/11 for the respective fixes in `@readme/oas-tooling` and `@readme/react-jsonschema-form`.
Check the updates to `types.json` for the example …
> fix: support for repairing malformed array schemas

- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
This resolves a bug in RJSF where if an integer or number schema within an `allOf` block had a `format` property, `json-schema-merge-allof` would fail (causing RJSF to fail) because `format` had no set up resolver for it on non-strings.
For example:
```json
"components": {
"schemas": {
"WorkItemStatusReason": {
"enum": [
0,
1,
2,
3,
4
],
"type": "integer",
"format": "int32"
},
"CaseModel": {
"type": "object",
"properties": {
"StatusReason": {
"allOf": [
{
"$ref": "#/components/schemas/WorkItemStatusReason"
}
]
}
},
"additionalProperties": false
}
}
}
```
Tests for this have been added to RJSF here: https://github.com/readmeio/react-jsonschema-form/pull/12
> chore(deps): upgrading @readme/react-jsonschema-form to 1.1.4

- packages/markdown/components/Callout/index.jsx
- packages/markdown/components/CodeTabs/index.jsx
- packages/markdown/components/Heading/index.jsx
- packages/markdown/index.js
With the inclusion of `identity-obj-proxy` in our Jest setup for mocking style imports, we no longer need these hacky exclusionary blocks of code.
If tests pass, we good.
> fix: removing some environmental exclusions of styles

- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
This updates `@readme/oas-tooling` to resolve a bug in our handling of `$ref` pointers where now if one is empty, we'll no longer try to process it.
We've seen this issue crop up on https://docs.hikeup.com/reference#customers_getall because most, if not all, of their `$ref` pointers are empty.
> chore(deps): upgrading @readme/oas-tooling to 3.1.5

- packages/markdown/package-lock.json
- packages/markdown/package.json
- packages/markdown/webpack.config.js
- packages/syntax-highlighter/codemirror.jsx
Swapping out the `isomorphic-style-loader` in favor of the default. This addresses some issues with broken CSS compilation and imports that were introduced in #537.
All guides, endpoint docs, and other content rendered via the `rdmd` directive should be appropriately styled. (Once this is merged and released I'll set up a PR in ReadMe proper where we can test out this fix.)
> Fix @readme/markdown CSS imports.

- packages/api-explorer/src/index.jsx
- packages/api-explorer/src/lib/get-auth.js
When passing an empty array through jwt in user.keys, it caused the entire reference section to break. This is what happens on our docs if a user logs in that doesn't have any projects in ReadMe.
Fixes README-FN
You can see this in action by commenting out lines 125 and 126 in Demo.jsx. Without this fix the reference section will show an error. 
> Fix error when passing an empty array for keys

- example/swagger-files/examples.json
- packages/api-explorer/__tests__/lib/create-code-shower.test.js
- packages/api-explorer/src/lib/create-code-shower.js
This fixes a bug in our spec coverage of response examples where if an example within an `examples` array had a `value` property, we were returning that whole object (value included) instead of the *contents* of the `value` property.
> fix: if we have a value property in an example, return that

- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
- fix: removing descriptions from top-level component schemas [`#153`](https://github.com/readmeio/oas/pull/153)
- fix: wouldn't add common params to a json schema if it was a $ref [`#152`](https://github.com/readmeio/oas/pull/152)
- chore(deps-dev): Bump auto-changelog from 1.16.3 to 1.16.4 [`#149`](https://github.com/readmeio/oas/pull/149)
- chore(deps-dev): Bump jest from 25.2.4 to 25.2.7 [`#150`](https://github.com/readmeio/oas/pull/150)
- chore(deps-dev): Bump @readme/eslint-config from 2.0.2 to 2.0.3 [`#151`](https://github.com/readmeio/oas/pull/151)
- chore(deps-dev): Bump prettier from 2.0.1 to 2.0.3 [`#148`](https://github.com/readmeio/oas/pull/148)
> chore(deps): upgrading @readme/oas-tooling to 3.1.7

- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
This upgrades  `@readme/react-jsonschema-form` to fix a bug with our handling of JSON Schema where if a schema with `allOf` had an adjacent `example` property, `json-schema-merge-allof` would throw a fatal error because `example` is an unknown JSON Schema property.
> chore(deps): upgrading @readme/react-jsonschema-form" to 1.1.5

- packages/api-explorer/src/Params.jsx
This slightly refactors the `Params` component so we don't unnecessarily re-process an operations parameters to JSON Schema anytime the state of the operations `Doc` changes.
If all tests pass, we're good.
> fix: refactoring when we're converting params to json schema

- packages/api-explorer/__tests__/lib/create-code-shower.test.js
- packages/api-explorer/src/lib/create-code-shower.js
Fixes a bug where an operation with multiple responses would have that example `value` object showed in full, instead of the contents of the `value` object.
> fix: bug where responses with multiple examples weren't rendered properly

- packages/api-explorer/__tests__/__fixtures__/example-results/oas.json
- packages/api-explorer/__tests__/lib/create-code-shower.test.js
- packages/api-explorer/src/lib/create-code-shower.js
This resolves a bug that cropped up in Sentry where if an operation response has an empty `examples` object (`examples: {}`), we'd try to parse it and ultimately fail when attempting to extract a `value` out of a non-object.
> fix: if an OAS has an empty examples object, don't parse it

- packages/markdown-magic/components/Heading.jsx
Fixes a case where docs are written as this:
https://developer.goacoustic.com/acoustic-content/reference#authoring-resources
> fix: cases where markdown headers dont have content

- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
This resolves some issues that are preventing projects from upgrading off our legacy API Explorer:
* https://productsup-component-docs.readme.io/reference?newApiExplorer=true#put_check-1
> fix: legacy api upgrade issues

- packages/markdown/__tests__/__snapshots__/index.test.js.snap
- packages/markdown/__tests__/index.test.js
- packages/markdown/index.js
- packages/markdown/package-lock.json
- packages/markdown/package.json
- packages/markdown/processor/plugin/index.js
- packages/markdown/processor/plugin/section-anchor-id.js
Fixes #622
Added a div with a section- prefix after all headings. Is this the correct place for them? Is `<div>` the right element?
See added unit tests
> Add compatibility #section- ID after all headers

- packages/syntax-highlighter/__tests__/__snapshots__/index.test.js.snap
- packages/syntax-highlighter/__tests__/index.test.js
- packages/syntax-highlighter/codemirror.jsx
- packages/syntax-highlighter/modes.js
This adds support for a heap of programming languages aliases that we:
* Said we supported, but didn't actually: `js`, `stylus`
* Should support because they're common aliases: `py` for Python, `rb` for Ruby, `js` for JS, `cpp` for C++
* Should support because they're similar flavors that we can already render: `mssql`, `pgsql`, `sqlite`
* Should support because people have been asking for it: `dart`
Our RDMD docs have already been updated to reflect this PR: https://docs.readme.com/rdmd/docs/code-blocks#highlighting
I've added comprehensive tests for every language we support now in `@readme/syntax-highlighter` with simple "Hello World" examples sourced from https://github.com/leachim6/hello-world.
> feat: adding support for a handful of language highlight aliases

- example/src/ApiList.jsx
- example/src/SpecFetcher.jsx
Benak uses this website to test OAS files that customers send us and he's asked for an easy way to view that spec file so I added a link to the currently viewed spec:
-----
Also added the ability to enter a URL in the UI:
Inline form:
Disabled option in the dropdown showing the URL:
----
We now also support yaml files!
http://localhost:9966/reference/?url=https://petstore.swagger.io/v2/swagger.yaml
http://localhost:9966/?selected=https%3A%2F%2Fpetstore.swagger.io%2Fv2%2Fswagger.yaml&customUrl=true
> Add button to open up viewed spec file

- packages/oas-to-har/__tests__/lib/remove-undefined-objects.test.js
- packages/oas-to-har/src/lib/remove-undefined-objects.js
This resolves a funky case with HAR generation where if a user clicks add an entry to an `array<primitive>` parameter, we would immediately add `[null]` into their code sample.
Why this was happening because if you supply `[undefined]` to `JSON.stringify`, it'll transform that into `[null]`, and we didn't have any work to filter out nullish items from arrays.
Load up http://localhost:9966/?selected=swagger-files%2Ftypes.json, head to the "Arrays of different data types" operation and play around with adding and removing arrays.
> fix: filter out nullish arrays from generated HAR objects

- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
This updates `@readme/oas-tooling` to fix a couple of issues with how we're compiling JSON Schema:
- fix: don't set a type on a properties key if that key is a param [`#172`](https://github.com/readmeio/oas/pull/172)
- fix: bug where a nested allOf/anyOf/oneOf parameter wasn't compiled [`#171`](https://github.com/readmeio/oas/pull/171)
> chore(deps): upgrading @readme/oas-tooling to 3.3.3

- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- fix: edge case where component would sometimes be marked a string [`#174`](https://github.com/readmeio/oas/pull/174)
> chore(deps): upgrading @readme/oas-tooling to 3.3.5

- packages/api-explorer/src/Doc.jsx
- packages/api-explorer/style/markdown-overrides.scss
> style(explorer): add .markdown-body class to excerpt

- packages/markdown/__tests__/__snapshots__/components.test.js.snap
- packages/markdown/__tests__/components.test.js
- packages/markdown/components/Callout/index.jsx
- packages/markdown/processor/parse/magic-block-parser.js
|[Asana]()|
|:-:|
* 🐛 I'm fixing a bug
> Fix magic block callout icons alignment.

- packages/markdown/components/Callout/style.scss
- packages/markdown/components/Code/style.scss
- packages/markdown/components/Image/Lightbox.jsx
- packages/markdown/components/Image/index.jsx
- packages/markdown/components/Image/style.scss
- packages/markdown/styles/gfm.scss
- packages/markdown/styles/main.scss
* 🆕 I'm adding something new
* 📸 I've made some changes to the UI!
> Keyboard accessible RDMD lightboxes.

- packages/markdown/components/Image/Lightbox.jsx
- packages/markdown/components/Image/index.jsx
This fixes a bug on Firefox where every light box would occasionally open on page load:
[![image](https://user-images.githubusercontent.com/886627/81215878-d632c180-8f8e-11ea-8773-ba1eac75c0f4.png)](https://readmeio.slack.com/files/U09PK6RK7/F013VM31AN4/screen_recording_2020-05-06_at_10.49.26_am.mov)
---
* 🐛 I'm fixing a bug
> Fix Firefox lightbox bug.

- packages/markdown/__tests__/__snapshots__/index.test.js.snap
- packages/markdown/__tests__/index.test.js
- packages/markdown/processor/parse/flavored/callout.js
- packages/markdown/processor/plugin/section-anchor-id.js
- packages/markdown/styles/gfm.scss
(the text value retains capitalization, where the `properties.id` we _were_ `kebab`-ing was already lowercased.)
* 🐛 I'm fixing a bug
> Fix RDMD camelCase anchor splitting.

- packages/markdown/components/Image/style.scss
Landscape images are displayed very awkwardly in the new light box. We should resize the dimensions based on a max-width so that _all_ images fit nicely within the viewport.
* 🐛 I'm fixing a bug
> Fix RDMD lightbox landscape aspect ratios.

- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
Updates `@readme/oas-tooling` to fix a bug where if a space was at the top of a server URL, it would fail HAR validation on all code samples we'd generate.
- fix: trim surrounding whitespace in server URLs [`#182`](https://github.com/readmeio/oas/pull/182)
- chore(deps): Bump oas-normalize from 2.0.2 to 2.1.0 [`#179`](https://github.com/readmeio/oas/pull/179)
- chore(deps-dev): Bump jest from 25.4.0 to 25.5.4 [`#176`](https://github.com/readmeio/oas/pull/176)
- chore(deps): Bump swagger-inline from 3.0.3 to 3.0.4 [`#177`](https://github.com/readmeio/oas/pull/177)
- chore(deps-dev): Bump @readme/eslint-config from 2.0.4 to 2.0.6 [`#178`](https://github.com/readmeio/oas/pull/178)
- chore: extracting the Operation class into its own file [`#175`](https://github.com/readmeio/oas/pull/175)
> fix: update @readme/oas-tooling to resolve a HARError bug

- packages/api-explorer/__tests__/ResponseSchema.test.jsx
- packages/api-explorer/src/ResponseSchema.jsx
The before & after:
Will open an integration PR in ReadMe and post a link to the demo app.
> Better code block dark theme in response schema sidebar.

- package-lock.json
- package.json
- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
- chore(deps): Bump swagger-inline from 3.0.4 to 3.0.5 [`#191`](https://github.com/readmeio/oas/pull/191)
- chore(deps): Bump oas-normalize from 2.1.0 to 2.2.0 [`#192`](https://github.com/readmeio/oas/pull/192)
- fix: resolving a bug where nested allOf schemas wouldn't get flattened [`#193`](https://github.com/readmeio/oas/pull/193)
- feat: bundle $refs, and other minor changes [`#190`](https://github.com/readmeio/oas/pull/190)
- chore(deps-dev): Bump lerna from 3.21.0 to 3.22.0 [`#189`](https://github.com/readmeio/oas/pull/189)
- chore(deps): Bump open from 7.0.3 to 7.0.4 [`#188`](https://github.com/readmeio/oas/pull/188)
- chore(deps-dev): Bump lerna from 3.20.2 to 3.21.0 [`#187`](https://github.com/readmeio/oas/pull/187)
- chore(deps): [Security] Bump acorn from 7.1.0 to 7.2.0 …
> chore(deps): upgrading @readme/oas-tooling

- packages/markdown/processor/plugin/section-anchor-id.js
Polish some more rough edges around section anchor generation. Specifically:
> Strip preceding dashes from anchor IDs.

- packages/markdown/processor/plugin/section-anchor-id.js
Per #713, emojis were being stripped from heading anchors and leaving extraneous dashes in their wake. Unfortunately, our fix for this ended up causing some breakage around the in-page linking feature for new search. Specifically, the migrated anchor data no longer matched the rendered markup for certain headings. So clicking an in-page hit from the new search results wouldn't navigate to the correct subsection! This PR reverts the dash sanitization originally added in #714.
> Remove RDMD anchor dash sanitization.

- package-lock.json
- package.json
- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/api-logs/package-lock.json
- packages/api-logs/package.json
- packages/http-status-codes/package-lock.json
- packages/http-status-codes/package.json
- packages/markdown-magic/package-lock.json
- packages/markdown-magic/package.json
- packages/markdown/package-lock.json
- packages/markdown/package.json
- packages/oas-extensions/package-lock.json
- packages/oas-extensions/package.json
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
- packages/syntax-highlighter/package-lock.json
- packages/syntax-highlighter/package.json
- packages/variable/package-lock.json
- packages/variable/package.json
* feat: toggling `require-await` on the `testing` config ([283dfa3](https://github.com/readmeio/eslint-config/commit/283dfa3))
* chore: setting up dependabot to keep an eye on our workflows ([56560ed](https://github.com/readmeio/eslint-config/commit/56560ed))
* build(deps-dev): bump eslint from 7.1.0 to 7.2.0 (#86) ([2cab7f1](https://github.com/readmeio/eslint-config/commit/2cab7f1)), closes [#86](https://github.com/readmeio/eslint-config/issues/86)
* build(deps): bump eslint-plugin-import from 2.20.2 to 2.21.1 (#85) ([8699711](https://github.com/readmeio/eslint-config/commit/8699711)), closes [#85](https://github.com/readmeio/eslint-config/issues/85)
* ci: create Dependabot config file (#84) ([0063b20](https://github.com/readmeio/eslint-config/commit/0063b20)), closes …
> chore(deps-dev): upgrading @readme/eslint-config to 3.2.0

- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
* fix: snippet paths should not include the server url (#77) ([a812f0b](https://github.com/readmeio/api/commit/a812f0b)), closes [#77](https://github.com/readmeio/api/issues/77)
* chore(deps-dev): bump lerna from 3.22.0 to 3.22.1 (#74) ([7c270c2](https://github.com/readmeio/api/commit/7c270c2)), closes [#74](https://github.com/readmeio/api/issues/74)
* chore(deps): bump @readme/oas-to-har from 6.10.0 to 6.10.2 (#73) ([1b4568c](https://github.com/readmeio/api/commit/1b4568c)), closes [#73](https://github.com/readmeio/api/issues/73)
* chore(deps): bump @readme/oas-tooling from 3.4.3 to 3.4.5 (#75) ([05e5204](https://github.com/readmeio/api/commit/05e5204)), closes [#75](https://github.com/readmeio/api/issues/75
> chore(deps): upgrading httpsnippet-client-api to 2.1.1

- example/swagger-files/cookies.json
- packages/oas-to-har/__tests__/__fixtures__/common-parameters.json
- packages/oas-to-har/__tests__/index.test.js
- packages/oas-to-har/src/index.js
This adds general support for cookie parameters into the explorer and our `oas-to-har` library.
Adding this because it's a deficiency of our OpenAPI support, and also the new `api` should support it and that uses `oas-to-har` for the bulk of its processing. If you click on "Node (simple)" in the demo site you'll see that it currently doesn't support cookies (see https://github.com/readmeio/api/issues/38).
I've added a grip of tests for cookies into the `oas-to-har` suite, all of which are identical to our tests for query string params. To see this in action, load up the demo site and check out the new `cookies` example:
> feat: adding support for cookies to oas-to-har

- example/swagger-files/formdata.json
- packages/api-explorer/__tests__/lib/generate-code-snippet.test.js
- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/oas-to-har/__tests__/index.test.js
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
- packages/oas-to-har/src/index.js
This resolves a couple bugs with how we're generating HAR definitions:
* This required an update to [fetch-har](https://npm.im/fetch-har) to support `postData.params`. See https://github.com/readmeio/fetch-har/pull/67 for details.
* This required an update to [fetch-har](https://npm.im/fetch-har) to support `postData` no longer being an expectation. See https://github.com/readmeio/fetch-har/pull/67 for details.
* Add those missing defaults to generated definitions.
* Update the unit test suite to assert that we're always generating valid HAR definitions when running our other assertions.
You can see this broken in action here: http://bin.readme.com/s/5efbb6ac35bcd40024d60488
Load up the local server and the `formData` example to see how it's handled how: …
> fix: issue where application/x-www-form-urlencoded payloads weren't being handled properly

- packages/oas-to-har/__tests__/index.test.js
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
I've decoupled the `toBeAValidHAR()` custom Jest matcher I added in #807 into its own package: [jest-expect-har](https://www.npmjs.com/package/jest-expect-har)
> test: loading in our new decoupled jest-expect-har package

- packages/markdown/__tests__/__snapshots__/flavored-compilers.test.js.snap
- packages/markdown/__tests__/flavored-compilers.test.js
- packages/markdown/index.js
- packages/markdown/package.json
- packages/markdown/processor/compile/figure.js
- packages/markdown/processor/compile/index.js
- packages/markdown/processor/compile/pin.js
- packages/markdown/processor/compile/table-head.js
- packages/markdown/processor/parse/index.js
💂‍♀️ [Sentry Ticket](https://sentry.io/organizations/readme/issues/1694192811)
|:---:|
> fix(markdown): add missing compilers

- packages/api-explorer/__tests__/CodeSample.test.jsx
- packages/api-explorer/src/CodeSample.jsx
- packages/oas-to-snippet/README.md
- packages/oas-to-snippet/__tests__/index.test.js
- packages/oas-to-snippet/jest.config.js
- packages/oas-to-snippet/package-lock.json
- packages/oas-to-snippet/src/index.js
This decouples the React syntax highlighting portion of `@readme/syntax-highlighter` from `@readme/oas-to-snippet` so it can be used in non-React environments.
While in the process of this, I slightly reworked how we render errors for cases where we can't generate a code snippet for a specific language and instead of rendering an empty box, we now show a friendly message:
Slightly reworked a lot of the unit tests so `@readme/oas-to-snippet` continues to assert that snippets are good, and left the existing tests in the `CodeSample` component of the Explorer alone since they already testing the full integration of `@readme/oas-to-snippet` + `@readme/syntax-highlighter`.
> fix: decouple react highlight from code snippets

- packages/oas-to-snippet/src/index.js
Adding the languages we support as an export, to be consumed as a cohesive list.
> chore(snippet): exporting supported langs

- packages/oas-to-snippet/package-lock.json
- packages/oas-to-snippet/package.json
Upgrades our `httpsnippet-client-api` package to allow for cleaner `api` code snippets:
Resolves https://github.com/readmeio/api-explorer/issues/823
> chore(deps): upgrading httpsnippet-client-api to 2.1.6

- example/swagger-files/auth-types.json
Use the GET /cookies httpbin endpoint to show the cookie data:
```sh
$ curl --request GET \
--url http://httpbin.org/cookies \
--cookie apiKey=456
{
"cookies": {
"apiKey": "456"
}
}
```
Test auth-types in demo app and run the code sample.
> docs: make cookie example better

- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
- packages/oas-to-snippet/package-lock.json
- packages/oas-to-snippet/package.json
Updates the Explorer to update `@readme/oas-tooling` to v3.5.2 in order to fix a problem where if an OAS operation was using the same security schemes multiple times across an `||` definition, it would get duped within the `AuthBox` component.
You can see this broken on http://bin.readme.com/s/5f0e11c383474c0024035f6f by clicking the auth box:
What it looks like now:
* fix: dedupe security schemes when plucking them out of an oas (#222) ([acb9bf1](https://github.com/readmeio/oas/commit/acb9bf1)), closes [#222](https://github.com/readmeio/oas/issues/222)
* docs: regenerating the changelog from scratch ([3d0d3f6](https://github.com/readmeio/oas/commit/3d0d3f6))
* chore: removing some unncessary deps from the lerna-level package ([5432dbe](https://github.com/readmeio/oas/commit/5432dbe))
* …
> chore(deps): upgrading @readme/oas-tooling to 3.5.2

- packages/markdown/styles/gfm.scss
🎫 [Ticket][ticket]
:---:
"Despecify" the ruleset that adds `text-decoration` to markdown links in order to better account for the hard override we have on this rule in ReadMe's [base CSS](https://github.com/readmeio/readme/blob/next/hub2/public/css/layout.styl#L21-L25).
[ticket]: https://app.asana.com/0/1183788502758137/1183776386684939/f
> style(rdmd): fix link text-decoration

- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
This updates `fetch-har` to resolve some improper handling of `application/x-www-form-urlencoded` payloads where they would be sent as JSON through the "Try It" request instead of as URLencoded data.
See https://github.com/readmeio/fetch-har/pull/69 for the fix, and https://app.asana.com/0/0/1183793140674162/f for background.
Here's a sample OAS you can test with to see it in action.
```json
{
"openapi": "3.0.0",
"info": {
"title": "urlencoded fix",
"version": "2.0"
},
"servers": [
{
"url": "http://httpbin.org"
}
],
"security": [
{
"basicAuth": []
}
],
"paths": {
"/post": {
"post": {
"operationId": "getToken",
"security": [
{
"basicAuth": []
}
],
"requestBody": {
"required": true,
"content": {
"application/x-www-form-urlencoded": {
"schema": {
"type": "object",
"properties": { …
```
> fix: improper handling of application/x-www-form-urlencoded payloads

- example/swagger-files/examples.json
- packages/api-explorer/__tests__/ExampleTabs.test.jsx
- packages/api-explorer/__tests__/ResponseExample.test.jsx
- packages/api-explorer/__tests__/ResponseSchema.test.jsx
- packages/api-explorer/__tests__/__fixtures__/example-results/oas.json
- packages/api-explorer/__tests__/__fixtures__/petstore/oas.json
- packages/api-explorer/__tests__/lib/create-code-shower.test.js
- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/api-explorer/src/IconStatus.jsx
- packages/api-explorer/src/ResponseSchema.jsx
| [🎫  Asana](https://app.asana.com/0/1177947654981875/1183804761024586/f) |
| :--- |
This adds support for `default` responses in operations.
You can see this lack of support here: http://bin.readme.com/s/5f10b79bbfe30000247ea10d
What it looks like now:
This also fixes an issue where `default` in the response dropdown wasn't capitalized:
And fixed:
> feat: adding support for handling `default` responses

- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/oas-to-har/__tests__/index.test.js
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
- packages/oas-to-snippet/package-lock.json
- packages/oas-to-snippet/package.json
This updates `@readme/oas-tooling` to resolve a bug where `operation.getContentType()` couldn't handle `requestBody` schemas that were stored in a `$ref`. This was exposed as a bug in a `multipart/form-data` request that was being improperly treated as `application/json` as since `getContentType()` didn't see any request bodies, it would default to JSON.
See https://github.com/readmeio/oas/pull/227 for that fix.
Resolves https://app.asana.com/0/1177947654981875/1175486497688586/f
You can see this broken here: http://bin.readme.com/s/5f12033dc8a6fe0024c39488
And fixed:
* fix: add support for $ref when pulling content types (#227) ([582968d](https://github.com/readmeio/oas/commit/582968d)), closes [#227](https://github.com/readmeio/oas/issues/227)
* build(deps): bump lodash from 4.17.15 to …
> fix: adding support for handling requestBody if its in a $ref

- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
Updates our fork of RJSF to pull in the potential fix for circular refs in https://github.com/readmeio/react-jsonschema-form/pull/14.
We have a demo circular ref definition that's currently failing here: https://preview.readme.io/?selected=swagger-files%2Fcyclical-refs.json
Loading it up locally via http://localhost:9966/?selected=swagger-files%2Fcyclical-refs.json you'll now see:
> feat: upgrading @readme/react-jsonschema-form to v1.2.0

- packages/markdown/components/Callout/style.scss
Fix vertical icon alignment for callouts with empty headings. Resolves #763.
> style(rdmd/callout): fix icon alignment

- packages/api-explorer/__tests__/lib/content-type-is-json.test.js
- packages/api-explorer/src/lib/content-type-is-json.js
This resolves a bug where vendored JSON content types, like `application/vnd.github.v3.star+json`, were being treated as plain text.
Resolves https://app.asana.com/0/1177947654981875/1186354765663162/f
You can see this bug in action here: http://bin.readme.com/s/5f285a019c025c00240f7a31
And fixed:
> fix: vendored json content types being treated as plain text

- packages/api-explorer/__tests__/__fixtures__/auth-types/no-security-schemes.json
- packages/api-explorer/__tests__/lib/is-auth-ready.test.js
- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/markdown-magic/package-lock.json
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
- packages/oas-to-snippet/package-lock.json
- packages/oas-to-snippet/package.json
This fixes a bug in our `Operation.getSecurity()` code where if an API definition had a valid `security` definition on either an operation or the root level, we'd return that even if they didn't have any `securitySchemes` set up.
This bug would expose itself by throwing a fatal error when attempting to make an API request.
See https://github.com/readmeio/oas/pull/259 for the bugfix in `@readme/oas-tooling`.
> fix: bug where if no securityschemes were present, we might return valid security

- packages/api-explorer/package-lock.json
- packages/markdown-magic/package-lock.json
- packages/oas-to-har/package-lock.json
- packages/oas-to-snippet/package-lock.json
- packages/oas-to-snippet/package.json
- packages/syntax-highlighter/package-lock.json
This upgrades `@readme/httpsnippet` to bring us the ability to generate cleaner code snippets for the Python `requests` library.
> chore(deps): upgrading @readme/httpsnippet to 2.1.0

- example/swagger-files/types.json
- packages/api-explorer/__tests__/Params.test.jsx
- packages/api-explorer/src/Params.jsx
- packages/api-explorer/src/form-components/DateTimeWidget.jsx
`<input type="datetime-local">` is not fully supported by all browsers, and when we pull the stock `DateTimeWidget` from RJSF in, browsers that don't support the native input run into a weird issue where the input acts as if it's disabled.
The reason it's happening is because RJSF does some unnecessary UTC conversion work this input (as far as I can tell at least from reading the MDN docs for browsers that natively support it), and when that work happens on browsers that can't handle it like Firefox they don't surface a TZ date `onChange`. When that happens, RJSF just returns an empty string, which in turn undoes any input that the user entered rendering the input effectively disabled.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local
Open up …
> fix: creating a custom DateTimeWidget for datetime-local inputs

- example/swagger-files/polymorphism.json
- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
- packages/oas-to-snippet/package-lock.json
- packages/oas-to-snippet/package.json
This fixes a bug in how we generate JSON Schema for the `Params` component where under certain conditions, `title` properties on polymorphism schemas (`oneOf`, `anyOf`, and `allOf`) would be deleted.
This also patches in a workaround for a bug in RJSF where if a `title` property is within a `$ref` and not at the level of the `$ref`, it wouldn't be used when constructing a dropdown for the schemas, instead displaying a placeholder label of "Option 1". [Bug ticketed here.](https://github.com/rjsf-team/react-jsonschema-form/issues/2016)
You can see this bug in action here: http://bin.readme.com/s/5f46ce04c46abe00244f41f6
Though the `Cat` and `Dog` schemas have a `title` property, it's not used in the dropdown.
With this fix, it now looks like:
> fix: issue where polymorphism titles in refs wouldn't be surfaced

- packages/api-explorer/__tests__/index.test.jsx
- packages/api-explorer/src/index.jsx
This fixes a case where user auth keys coming into the Explorer might not have an `id` present, but have everything else we need. For example:
```js
{
user: {
keys: [
{ apiKey: 'Bearer Sp63rycwm', name: 'App 2' },
{ apiKey: 'Bearer NBxd4epaZ', name: 'App 1' },
],
},
}
```
Right now, since `id` is missing, when you toggle between apps in the `AuthBox` dropdown we are throwing the following error:
So instead of doing that, if `id` is missing, but we've got a `name` in the key present, we're now using that to do auth determinations from the `AuthBox` dropdown to pick the right API key from our stored user keys.
> fix: cases where user auth keys might not have an `id` present

- example/swagger-files/cyclical-refs.json
- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
This upgrades `@readme/react-jsonschema-form` to v1.2.1 to resolve an issue introduced in v1.2.0 where we stopped processing schemas that were cyclical, but ones that were so in a safe way that wouldn't cause infinite recursion.
Check https://github.com/readmeio/react-jsonschema-form/pull/15 for more details on the problem and the actual fix.
You can see an example of this in the `/not-quite-cyclical` example I added into the `cyclical-refs` example definition, which you can also see here: http://bin.readme.com/s/5f63f9352fd27d002432212a
Before our fix, this operation wouldn't have any body parameters rendered:
But now:
> chore(deps): upgrading @readme/react-jsonschema-form to 1.2.1

- example/swagger-files/types.json
- packages/api-explorer/__tests__/Params.test.jsx
- packages/api-explorer/package-lock.json
- packages/api-explorer/src/Params.jsx
This reverts the changes to `date` and `date-time` that were introduced in https://github.com/readmeio/api-explorer/pull/895.
The `datetime-local` input isn't widely supported, and doesn't properly support datetimes so we're reverting and treating them, and `date` inputs, as simple strings for the indefinite future.
> fix: reverting `date` and `date-time` changes in #895

- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/api-explorer/src/CodeSample.jsx
- packages/api-explorer/src/ResponseBody.jsx
- packages/api-explorer/src/ResponseExample.jsx
- packages/api-explorer/src/block-types/CodeElement.jsx
- packages/oas-to-snippet/package-lock.json
- packages/oas-to-snippet/package.json
* fix(bundle): client and server compatibility (#20) ([bd4362b](https://github.com/readmeio/syntax-highlighter/commit/bd4362b)), closes [#20](https://github.com/readmeio/syntax-highlighter/issues/20)
* chore(deps-dev): bump @commitlint/cli from 9.1.2 to 11.0.0 (#10) ([c466e8d](https://github.com/readmeio/syntax-highlighter/commit/c466e8d)), closes [#10](https://github.com/readmeio/syntax-highlighter/issues/10)
* chore(deps-dev): bump @commitlint/config-conventional (#19) ([b700798](https://github.com/readmeio/syntax-highlighter/commit/b700798)), closes [#19](https://github.com/readmeio/syntax-highlighter/issues/19)
* chore(deps-dev): bump css-loader from 3.6.0 to 4.3.0 (#16) ([e3c0c67](https://github.com/readmeio/syntax-highlighter/commit/e3c0c67)), closes …
> chore(deps): upgrading @readme/syntax-highlighter to 10.0.0

- packages/markdown-magic/index.js
Fixes this error here: https://developers.logitech.com/circle/reference/accessories-api
```
mdast-util-to-hast: deprecation: `allowDangerousHTML` is nonstandard, use `allowDangerousHtml` instead
```
> fix: camelcase "allowDangerousHtml"

- packages/api-explorer/__tests__/Params.test.jsx
- packages/api-explorer/__tests__/__fixtures__/polymorphism/oas.json
- packages/api-explorer/src/form-components/SchemaField.jsx
This fixes an edge case where if a `format` was not present on a schema, we'd add `format: undefined` to it. The problem with doing this however is that on a case of a schema that has no `type` but `readOnly` and `allOf`, we'd create an `allOf` schema that was unable to be handled properly. Reason for this is that deep inside the form module we use [json-schema-merge-allof](https://www.npmjs.com/package/json-schema-merge-allof) that attempts to merge `allOf` schemas into something we can render, but with `format: undefined` at this level it'd try to merge the following arrays into each other and fail:
```js
[
{readOnly: true, format: undefined},
{allOf: [...]}
]
```
Remove `format: undefined` and it works as expected. Why was `format: undefined` being added in the first place though? Well …
> fix: don't set an undefined format on the schema if we don't recognize it

- packages/api-explorer/__tests__/form-components/DescriptionField.test.jsx
- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/api-explorer/src/Doc.jsx
- packages/api-explorer/src/ResponseSchema.jsx
- packages/api-explorer/src/ResponseSchemaBody.jsx
- packages/api-explorer/src/block-types/Content.jsx
- packages/api-explorer/src/form-components/DescriptionField.jsx
Upgrades `@readme/markdown` to take advantage of the new `copyButtons` option I introduced in https://github.com/readmeio/markdown/pull/59 to allow us to hide copy buttons from showing up in rendered `code` markdown.
Copy buttons are visible here: http://bin.readme.com/s/5f879491410c3700243caa57
With this update:
> chore(deps): upgrading @readme/markdown to hide code copy buttons

- packages/oas-to-snippet/__tests__/__snapshots__/index.test.js.snap
- packages/oas-to-snippet/__tests__/index.test.js
- packages/oas-to-snippet/package-lock.json
- packages/oas-to-snippet/package.json
- packages/oas-to-snippet/src/index.js
> feat: swapping request module node samples with node-fetch

- packages/oas-to-snippet/package-lock.json
- packages/oas-to-snippet/package.json
This upgrades the `node-simple` code snippet generator to fix a couple issues, namely being that `Basic` auth wasn't being decoded for `sdk.auth()` calls.
With the fixes in the library:
Resolves https://github.com/readmeio/api-explorer/issues/832
You can test out basic auth with the [auth-types](http://localhost:9966/?selected=swagger-files%2Fauth-types.json) definition.
* chore: test cleanup (#181) ([1fe0e95](https://github.com/readmeio/api/commit/1fe0e95)), closes [#181](https://github.com/readmeio/api/issues/181)
* fix: adding support for non-alphanumerical operation ids (#180) ([fd075a0](https://github.com/readmeio/api/commit/fd075a0)), closes [#180](https://github.com/readmeio/api/issues/180)
* fix: basic auth headers now decoded and exploded into `.auth()` calls (#179) …
> fix: issue in node-simple snippets where basic auth wasn't decoded

- packages/oas-to-snippet/src/index.js
In the same vain as https://github.com/readmeio/api-explorer/commit/4bf746474d27e37059f5be777c9dcd9ff0ae5785
Switching javascript target from xhr to fetch
Tested here against petstore: http://localhost:9966/
Tested here to make sure variables are passed through: http://localhost:9966/?selected=swagger-files%2Fauth-types.json
One thing I've not tested is cookies and the credentials option that can be passed in to fetch: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Sending_a_request_with_credentials_included
> fetch won’t send cookies, unless you set the credentials init option. (Since Aug 25, 2017. The spec changed the default credentials policy to same-origin. Firefox changed since 61.0b13.)
We used to say `cors: false` for the xhr config, which I think is the …
> feat: set default javascript target to use fetch instead of xhr

- packages/api-explorer/__tests__/ResponseSchemaBody.test.jsx
- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/api-explorer/src/ResponseSchemaBody.jsx
- packages/markdown-magic/package-lock.json
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
- packages/oas-to-snippet/package-lock.json
- packages/oas-to-snippet/package.json
With https://github.com/readmeio/oas/pull/292, `oas/tooling/lib/flattenSchema` is now an async library to enable us to properly handle circular `$ref` pointers when flattening a response in the `ResponseSchemaBody` component.
This change updates the `ResponseSchemaBody` component to be compatible with the changes incoming in https://github.com/readmeio/oas/pull/292.
Here's an example of a circular ref'd schema that's currently failing when we're flattening the response schema: http://bin.readme.com/s/5f8f6eec31f4240024e73488
> fix: updating the ResponseSchemaBody for the async flattenSchema changes

- packages/oas-form/__tests__/utils_test.js
This test to evaluate that `React.memo()` widgets in `@readme/oas-form` work is broken due to some differing React versions in place now that we're hoisting deps. Since we don't use `React.memo()` anywhere, and neither is it used anywhere within `oas-form` I'm commenting this test out.
> test: skipping a broken ReactIs test

- package-lock.json
- package.json
- packages/oas-to-snippet/__tests__/index.test.js
- packages/oas-to-snippet/package-lock.json
- packages/oas-to-snippet/package.json
Upgrades `@readme/httpsnippet` to 2.2.3 to remove unnecessary `.toString()` calls when supplying `URLSearchParams` to `node-fetch` body` options.
`node-fetch` can accept both a string or the raw object, so since the snippet looks cleaner without the stringification we're removing it.
> chore: remove unnecessary stringification from node-fetch snippets

- packages/api-explorer/__tests__/Params.test.jsx
- packages/api-explorer/src/Params.jsx
- packages/oas-extensions/index.js
This fixes a regression that was introduced in https://github.com/readmeio/api-explorer/pull/940 where if you edited an input that was inside of an `ArrayField`, your browser would immediately lose focus. The reason for this happening is that since the form is dynamic we were recreating every form component and element anytime a state change would occur.
This bug was originally fixed in https://github.com/readmeio/api-explorer/commit/2313073711f3bb7b40df6e33eaf403e62caa22a3 by changing the way we create parameters for the form to be a stored component in `Doc`, but we accidentally undid this by moving those component creations back into the React function call that happens when the form reloads when we added support for operation-level extensions.
And to compound on that, we didn't know …
> fix: regression in focus being lost when editing inputs in arrays

- package-lock.json
- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/oas-to-snippet/package-lock.json
- packages/oas-to-snippet/package.json
* feat: adding support for TOML highlighting (#26) ([b2e617b](https://github.com/readmeio/syntax-highlighter/commit/b2e617b)), closes [#26](https://github.com/readmeio/syntax-highlighter/issues/26)
> chore(deps): upgrading `@readme/syntax-highlighter`

- packages/api-explorer/style/main.scss
The new response example work in https://github.com/readmeio/api-explorer/pull/1027 introduced a new problem of large response schemas potentially blowing up the length of the page.
> style: making the response example section scrollable

- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/api-explorer/src/lib/content-type-is-json.js
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
- packages/oas-to-snippet/package-lock.json
- packages/oas-to-snippet/package.json
> chore(deps): upgrading oas to 5.2.1

- packages/api-explorer/src/index.jsx
* Adding support for passing an optional function to handle group change via props (which is called in addition to existing, built-in behavior).
* This function would receive the new group member id whenever onAuthGroupChange() is invoked.
🧪 Testing
* Manually verified
> feat(api explorer): adding optional handler for auth group change

- package-lock.json
- packages/oas-to-snippet/__tests__/index.test.js
- packages/oas-to-snippet/package.json
- packages/oas-to-snippet/src/index.js
- packages/oas-to-snippet/src/supportedLanguages.js
replace stringified request body with JSON.stringify and object
The request body in the node example must be a string. Originally we were translating the JSON object to a string and including that. A JSON.stringified object is difficult to read, so this PR keeps the object literal and wraps it in a JSON.stringify call in the example.
See https://app.asana.com/0/1199087650851461/1198986894847661 for more discussion and example pictures.
Go to the petstore example, and the "add a new pet"  API call. Start typing in the "category" request body form below the example, and you should see the example automatically update with a request body that is an object literal wrapped in JSON.stringify.
> chore(oas-to-snippet): replace stringified request body with JSON.stringify and object

- example/reference/index.html
Removing the giant space on [the demo reference page](https://preview.readme.io/reference/) and force the sidebar to be a more normal color.
**Before:**
**After:**
Provide as much information as you can on how to test what you've done.
[Asana link](https://app.asana.com/0/1199087650851461/1199187472127725)
> Style: fix padding and color on the demo reference page

- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/api-explorer/webpack.config.js
Like we did with React in #1005 this chunks `@readme/markdown` out into a peerDependency and a Webpack external.
And because it's no longer in our compiled dist we also get some great reductions in bundle size:
```
$ du -hs packages/api-explorer/dist
4.9M	packages/api-explorer/dist
```
```
$ du -hs packages/api-explorer/dist
3.6M	packages/api-explorer/dist
```
> refactor: splitting rdmd out as an external dep

- packages/api-explorer/__tests__/ResponseSchemaBody.test.jsx
- packages/api-explorer/src/ResponseSchemaBody.jsx
This flips the order of data we're showing in the response schema component on operations from `type` → `property` to `property` → `type`.
You can test this out on the petstore example under the "Finds Pets by status" operation. Some examples:
> feat: flipping the order of data in the response schema component

- example/src/Demo.jsx
> style: move options in to a <Dropdown>

- packages/api-explorer/src/ResponseTabs.jsx
Before (Firefox and chrome only):
After:
> fix(examples): fix examples button type

- packages/api-logs/__tests__/index.test.jsx
- packages/api-logs/index.jsx
This stops us from fetching logs for users who aren't logged in.
You can test this by loading up `example/src/Demo.jsx` and changing the `user` variables prop to be an empty object. Refresh the page and you shouldn't see any requests towards `/api/logs`. Revert the change to fake a logged in state and logs should be retrieved.
> fix: dont fetch logs for users who aren't logged in

- packages/api-explorer/__tests__/lib/upgrade-legacy-responses.test.js
- packages/api-explorer/src/lib/upgrade-legacy-responses.js
Before this PR, legacy apps that used status code ranges (1XX, 2XX, 3XX, 4XX and 5XX) in their responses failed to show those responses in the non-legacy API explorer.
- Create a legacy project by disabling the new api explorer in the project configuration
- Manually create an API call with a response status code of 4XX. Make sure to include an example response body.
- View the project in the legacy API explorer, and see the 4XX status code in the response examples
- Enable the new API explorer from the project configuration
- View the project in the new API explorer. Before this PR you would not see the 4XX status code. After this PR you should see it.
> fix(api-explorer): fix legacy status ranges (4XX, etc)

- packages/api-explorer/src/ResponseSchema.jsx
This fixes a bug where sometimes switching what response schema you were looking at wouldn't update the component.
Resolves #1042
You can see this bug in action on the preview site here: http://bin.readme.com/s/5fc975f4a698920024f1aa95
Despite `200` and `2XX` having different responses, moving between them doesn't update the component, but if I move from `2XX` to `400` and then to `200` I'll see all three states.
Here's what this behavior looks like now with this fix:
<details>
<summary>API definition to test with</summary>
```json
{
"openapi": "3.0.3",
"info": {
"version": "1",
"title": "Bug Example API"
},
"servers": [
{
"url": "https://example.com"
}
],
"paths": {
"/example": {
"get": {
"responses": {
"200": {
"description": "200 response",
"content": {
"x-www-form-urlencoded": { …
```
> fix: issue where changing response schemas wouldn't always update the component

- package-lock.json
- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/oas-to-snippet/package-lock.json
- packages/oas-to-snippet/package.json
* chore(deps-dev): removing an unused dependency ([7cb08a0](https://github.com/readmeio/syntax-highlighter/commit/7cb08a0))
* feat(syntax-highlighter): support classname (#52) ([d5ae061](https://github.com/readmeio/syntax-highlighter/commit/d5ae061)), closes [#52](https://github.com/readmeio/syntax-highlighter/issues/52)
> chore(deps): upgrading @readme/syntax-highlighter to 10.4.1

- packages/oas-to-har/src/index.js
> fix: only access the proxy-enabled extension if we need to

- packages/api-explorer/__tests__/ResponseSchemaBody.test.jsx
- packages/api-explorer/src/ResponseSchemaBody.jsx
There's some problems with readmeio/api-explorer#1065 on some customer sites where the change makes property names look like crap:
Reverting this and we'll just handle the flip with the upcoming redesign.
> revert: "feat: flipping the order of data in the response schema component"

- packages/api-explorer/__tests__/CopyCode.test.jsx
- packages/api-explorer/src/CopyCode.jsx
This fixes a bug where it takes two clicks on the code sample copy button to copy the snippet you're looking at.
Bug is in production: https://preview.readme.io/
1. Click the copy button on a code sample. The code you're looking at should exist in your clipboard.
2. Click on another language tab.
3. Click the copy button. Code from the previous tab will still be in your clipboard.
4. Click the copy button again. Code from the new tab should be in your clipboard.
> fix: bug where it takes two clicks to get a code snippet to copy

- package-lock.json
- packages/oas-form/package-lock.json
- packages/oas-form/package.json
- packages/oas-form/src/components/fields/ArrayField.js
| 🎫 [Asana Task](https://app.asana.com/0/1199087650851461/1199553290437389/f) |
|--------------------------------------------------------------------------------------|
[shortid has been deprecated](https://www.npmjs.com/package/shortid). They recommend using `nanoid` — this just swaps `shortid` with `nanoid`.
Click on the Add button for those params to make sure you can add rows. 
1. Open up the local environment
2. Open a Swagger file that has object and array type parameters. `types.json` is a good one cause it will have all different types of params!
3. Find any parameter that requires you to Add a row of input like `array of strings` or `array of objects`. 
4. Click Add! If you can add rows, it should be good to go 😄
> refactor: use nanoid instead of shortid

- package-lock.json
- package.json
- packages/api-explorer/package-lock.json
- packages/oas-form/package-lock.json
- packages/variable/package-lock.json
Bumps the ui version to fix the theme default:
> chore(deps): bump ui to 1.17.3

- package-lock.json
- package.json
- packages/api-explorer/package.json
Bumps ui for updated tutorial tile component (it'll now say, "open recipe"):
> chore(deps): bump ui to 1.17.6

- packages/oas-to-har/__tests__/index.test.js
- packages/oas-to-har/src/index.js
Null values or defaults had the potential of throwing an error when rendering a non-body operation. This fixes that.
Message me for an example json file and put it in your `examples/swagger-files` folder, run `npm start`, and test the `manual-api-keeptrucking.json` file. Look for the endpoint named `driver_utilization`. Before this change you would see an error. After it you should see a rendered operation.
> fix(api-explorer): prevent nulls from breaking operations

- package-lock.json
- package.json
- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
- packages/oas-to-snippet/package-lock.json
- packages/oas-to-snippet/package.json
> fix: upgrade oas to fix a jsonpointer usage error

- packages/oas-to-har/__tests__/lib/style-formatting/index.test.js
- packages/oas-to-har/src/lib/style-formatting/index.js
- packages/oas-to-har/src/lib/style-formatting/style-serializer.js
| --- |
See unit test for examples.
> fix: ignore styling definitions on oas-reserved headers

- example/src/Demo.jsx
- packages/api-explorer/src/Doc.jsx
| --- |
Now that we've migrated our full component library to the ReadMe repo, we need to remove a stylesheet import from the API Explorer repo since it's being applied twice. See https://github.com/readmeio/readme/pull/3552 for more info!
I verified that this doesn't break any of the styling in the demo app because of [`bundle-hub2.css`](https://github.com/readmeio/api-explorer/blob/0b3fbebdaefd2306e6fe393a1c05dc781f9ffa7e/example/bundle-hub2.css).
This also does a bit of recipes-specific housekeeping:
Verify that the "Enable recipes" toggle in the demo app is working, and that none of the styling appears to be broken.
> fix(ui components): remove a stylesheet import that's now redundant

- package-lock.json
- packages/oas-to-snippet/__tests__/index.test.js
- packages/oas-to-snippet/package-lock.json
- packages/oas-to-snippet/package.json
- packages/oas-to-snippet/src/index.js
| --- |
Fixes a bug where if a query string had a `style` attribute to specify an encoding, it would end up getting doubly encoded between `@readme/oas-to-har` and `@readme/httpsnippet`.
Fixes RM-216
Check out the attached unit test. `2019-06-13T19:08:25.455Z` and `2015-09-15T14:00:12-04:00` was entered by the user and according to the API definition should be encoded with `form` styling. This data gets saved as `2019-06-13T19%3A08%3A25.455Z` into the HAR and fed into `@readme/oas-to-snippet` and `@readme/httpsnippet`.
`@readme/httpsnippet` should not encode this data again into `2019-06-13T19%253A08%253A25.455Z`.
[demo]: https://readme-api-e-fix-querys-rdllnu.herokuapp.com/
> fix: prevent code snippets from double encoding querystrings

- packages/api-explorer/__tests__/lib/parse-response.test.js
The condition at the end of this line didn't have a test:
https://github.com/readmeio/api-explorer/blob/77b90ebed4673f168354cdcd730e34b7ee016360/packages/api-explorer/src/lib/parse-response.js#L15
If the build passes 🤷‍♂️
> chore: add missing test for the wildcard response type branch

- package-lock.json
- package.json
- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
- packages/oas-to-snippet/package-lock.json
- packages/oas-to-snippet/package.json
> fix: bug where we'd crash if `examples` was an empty object

- example/swagger-files/manual-api-missingInOas.json
- package-lock.json
- package.json
- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
- packages/oas-to-snippet/package-lock.json
- packages/oas-to-snippet/package.json
| --- |
Check out the attached `manual-api-missingInOas.json` example definition.
Against `next`, this is what it currently looks like:
And with this fix:
> fix: missing operation schema exceptions

- package-lock.json
- packages/api-explorer/__tests__/ResponseBody.test.jsx
- packages/api-explorer/__tests__/ResponseExample.test.jsx
- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/api-explorer/src/ResponseBody.jsx
- packages/api-explorer/src/ResponseExample.jsx
| --- |
This updates [react-json-view](https://npm.im/react-json-view) to take advantage of the new `displayArrayKey` prop that allows us to hide array keys in JSON content from being rendered.
Before:
After:
> fix: stop rendering array keys in json content

- package-lock.json
- package.json
- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
- packages/oas-to-snippet/package-lock.json
- packages/oas-to-snippet/package.json
| --- |
This updates our `oas` dependency to fix two issues:
See the linked PRs in the `oas` repo for associated tests.
> chore(deps): upgrading oas to 10.0.4

- example/swagger-files/types.json
- packages/api-explorer/__tests__/Params.test.jsx
- packages/api-explorer/__tests__/__fixtures__/string/oas.json
- packages/oas-form/src/components/widgets/BaseInput.js
| --- |
See the `types.json` example and the accompanying unit test.
> feat: start exposing `pattern` attributes in schemas

- package-lock.json
- packages/oas-to-snippet/package-lock.json
- packages/oas-to-snippet/package.json
> fix: upgrading httpsnippet to fix a ruby ssl exploit

- package-lock.json
- package.json
- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/oas-form/package-lock.json
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
- packages/oas-to-snippet/package-lock.json
- packages/oas-to-snippet/package.json
| --- |
This updates our `oas` dependency to fix a bug where shapeless children of an `allOf` would receive a `type` when they shouldn't. For example:
```
allOf: [
{ 
type: 'array', 
items: { 
type: 'string' 
}
}, 
{ description: 'Parameter description' } // This ends up receiving `type: string`.
],
```
This also pulls in some JWT default handling that's being integrated within https://github.com/readmeio/api-explorer/pull/1189.
This [AWS Workspaces](https://preview.readme.io/?selected=https%3A%2F%2Fapi.apis.guru%2Fv2%2Fspecs%2Famazonaws.com%2Fworkspaces%2F2015-04-08%2Fopenapi.json) spec fails on the preview site.
But works now with this fix.
* fix: edgecase where allOfs would receive a `type` when one wasn't present (#374) …
> fix: updating oas to fix a bug with shapeless allOf child schemas

- packages/oas-form/src/components/widgets/BaseInput.js
| --- |
This updates the prop type on the `placeholder` prop in `BaseInput` to accept strings **and** numbers.
With this fix, this React error goes away:
```
Warning: Failed prop type: Invalid prop `placeholder` of type `number` supplied to `BaseInput`, expected `string`.
in BaseInput (created by UpDownWidget)
in UpDownWidget (created by Component)
in Component (created by StringField)
in StringField (created by NumberField)
in NumberField (created by SchemaField)
in div (created by CustomTemplate)
in div (created by CustomTemplate)
in CustomTemplate (created by SchemaField)
in SchemaField (created by SchemaField)
in SchemaField (created by ObjectField)
in fieldset (created by DefaultObjectFieldTemplate)
in DefaultObjectFieldTemplate (created by ObjectField) …
```
> fix: update the prop type on `placeholder` to accept numbers

- example/src/Demo.jsx
- jest.config.js
- package-lock.json
- package.json
- packages/api-explorer/__tests__/Doc.test.jsx
- packages/api-explorer/__tests__/Params.test.jsx
- packages/api-explorer/__tests__/index.test.jsx
- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/api-explorer/src/Doc.jsx
- packages/api-explorer/src/Params.jsx
- packages/api-explorer/src/index.jsx
| --- |
Last month we deprecated `@readme/ui`, but unfortunately our API Explorer still ships with it. This work fully decouples that library from this codebase, which'll allow to keep the components that we use here up to date with while also allowing us to shave a nice chunk off the bundle size.
Now when we instantiate the `APIExplorer` component in ReadMe we'll need to pass it a `ui` prop containing the following:
```js
{
// @readme/ui/.bundles/es/ui/components/Button
Button, 
// @readme/ui/.bundles/es/ui/components/Tabs
Tabs,
tutorials: {
// @readme/ui/.bundles/es/ui/compositions/Tutorials/Modal/constants/stepDefaults.DEFAULT_TUTORIAL
DEFAULT_TUTORIAL, 
// @readme/ui/.bundles/es/ui/compositions/TutorialModal
TutorialModal,
// …
```
> refactor: decoupling our ui library from the api explorer codebase

- packages/oas-to-har/__tests__/index.test.js
- packages/oas-to-har/src/index.js
| --- |
Our expected behavior with parameters set to `format=json` is that the resulting example is parsed into a JSON object. If it's valid JSON, it would appear as is in the example (`{"example": "code"}`). If invalid, it would show up as a string (`"{\"example\":\"code"`)
Before this PR, if you had two parameters in the same operation that were `format=json` and one was valid, but the other was not (or was left empty), neither parameter would be considered valid and they both would be turned into strings.
After this PR, any valid parameter should be properly formatted in the example.
Message me for a example OAS file, or find it in our internal ticketing, or create an OAS file with a single path, a single operation, and two parameters, each with …
> fix(oas-to-har): fix validation failures when using multiple json formats

- packages/oas-to-snippet/src/supportedLanguages.js
| --- |
I did work in `@readme/httpsnippet` in https://github.com/readmeio/httpsnippet/pull/34 to extend the `useObjectBody` option we have for `node-fetch` snippets over to JS `fetch`, but failed to turn it on within `@readme/oas-to-snippet`.
https://preview.readme.io/
> fix: enabling useObjectBody on js fetch snippets

- packages/oas-to-har/__tests__/index.test.js
- packages/oas-to-har/src/index.js
| --- |
When your request body has a type of `string` and format of `json`, the exact value was showing up as the user inputted string (with any included formatting (such as newlines)), passed through JSON.stringify .
e.g.
`--data='"{\n    \"foo\": \"bar\"\n}"'`
This changes that field to now appear as a JSON object passed thorugh JSON.stringify
e.g.
`--data='{"foo":"bar"}'`
Check the tests, or message me and I'll send you an example OAS file.
> fix(oas-to-har): clean up formatting of raw json bodies

- package-lock.json
- package.json
- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
- packages/oas-to-snippet/package-lock.json
- packages/oas-to-snippet/package.json
* feat: addition of a new `getAuth` method on the OAS class (#376) ([78c506b](https://github.com/readmeio/oas/commit/78c506b)), closes [#376](https://github.com/readmeio/oas/issues/376)
> chore(deps): upgrading oas to 10.2.0

- packages/api-explorer/__tests__/__fixtures__/polymorphism/discriminators.json
- packages/api-explorer/__tests__/form-components/MultiSchemaField.test.jsx
- packages/api-explorer/src/form-components/MultiSchemaField.jsx
> fix: bug with improperly placed discriminators

- packages/variable/__tests__/index.test.jsx
- packages/variable/index.jsx
| Fixes CX-166 |
| --- |
Allows variables to contain periods `.`.
[Broken on prod](https://kjp.readme.io/docs/variables-with-periods)
> feat: allow periods in variable regex

- packages/oas-extensions/__tests__/index.test.js
- packages/oas-extensions/index.js
> feat: adding new extensions for code and response samples

- package-lock.json
- packages/oas-to-snippet/package-lock.json
- packages/oas-to-snippet/package.json
Upgrading `httpsnippet-client-api` to 3.0 to pull in some changes that were done here: https://github.com/readmeio/api/pull/240
> chore(deps): upgrading httpsnippet-client-api

- packages/oas-extensions/__tests__/index.test.js
- packages/oas-extensions/index.js
Ports over a new `validateExtension` method into `oas-extensions` that we've had in place in readme/readme, while also adding support for the new `x-readme` grouping.
I've also removed the `RESPONSE_SAMPLES` extension I added yesterday as we don't actually need it.
> feat: adding a new `validateExtension` method to `oas-extensions`

- package-lock.json
- package.json
- packages/api-explorer/package-lock.json
- packages/api-explorer/package.json
- packages/oas-extensions/package-lock.json
- packages/oas-to-har/README.md
- packages/oas-to-har/__tests__/__fixtures__/server-variables.json
- packages/oas-to-har/__tests__/index.test.js
- packages/oas-to-har/package-lock.json
- packages/oas-to-har/package.json
- packages/oas-to-har/src/index.js
- packages/oas-to-snippet/package-lock.json
- packages/oas-to-snippet/package.json
> feat: adding support for server variables into oas-to-har

- packages/oas-to-snippet/__tests__/__snapshots__/index.test.js.snap
- packages/oas-to-snippet/__tests__/index.test.js
- packages/oas-to-snippet/src/index.js
| --- |
Allows for a separate HAR to be supplied to `@readme/oas-to-snippet` to create a code snippet for that passed in HAR object.
See unit tests.
> feat: allowing for a HAR override to be passed in for snippet creation

- packages/oas-to-har/__tests__/lib/configure-security.test.js
- packages/oas-to-har/src/lib/configure-security.js
This fixes a bug in `@readme/oas-to-har`'s `configure-security` library where if an OAS with a basic auth scheme does not exist within the provided auth data, and that auth data is **not** an empty object, we'd throw a fatal error when attempting to access `.user` on `undefined`
See tests
> fix: fatal error where basic auth scheme might be missing

- package-lock.json
- packages/oas-to-snippet/__tests__/__snapshots__/index.test.js.snap
- packages/oas-to-snippet/package-lock.json
- packages/oas-to-snippet/package.json
| --- |
This fixes a host of issues with snippet generation across a couple languages and targets:
* This pulls in a fix to have JS `fetch` snippets return `response.json()`. https://github.com/Kong/httpsnippet/pull/210
Provide as much information as you can on how to test what you've done.
> fix: upgrading snippet dependencies to fix various issues

- packages/oas-to-har/__tests__/index.test.js
- packages/oas-to-har/src/index.js
This fixes a bug with `application/x-www-url-formencoded` handling within `@readme/oas-to-har` where we weren't properly filtering out `undefined` values from `formData` before processing it into `postData` resulting in a case where if you added and removed data from the form we'd send `'undefined'` into the HAR (and thus into code snippets).
https://user-images.githubusercontent.com/33762/115469756-1617a680-a1ea-11eb-8f0c-abb48ef60e2c.mov
You can see this in action on https://preview.readme.io/?selected=swagger-files%2Fformdata.json
With this fix:
https://user-images.githubusercontent.com/33762/115469860-3cd5dd00-a1ea-11eb-8f7e-35a9f4c2bb9f.mov
> fix: removing undefined formData before processing it into postData

- example/src/SpecFetcher.jsx
> feat: tunnel OAS url requests through our CORS proxy

- packages/api-explorer/src/block-types/Content.jsx
| [☁️ &nbsp; CI App][demo] | Fix CX-281 |
| --- | --- |
Revert adding copy buttons to schema descriptions. 
https://github.com/readmeio/api-explorer/pull/1258#discussion_r622393687
Provide as much information as you can on how to test what you've done.
> fix: dont put copy buttons schema descriptions

- package-lock.json
- packages/oas-to-snippet/README.md
- packages/oas-to-snippet/__tests__/__snapshots__/index.test.js.snap
- packages/oas-to-snippet/__tests__/index.test.js
- packages/oas-to-snippet/package-lock.json
- packages/oas-to-snippet/package.json
- packages/oas-to-snippet/src/index.js
- packages/oas-to-snippet/src/supportedLanguages.js
| --- |
This updates `@readme/oas-to-snippet` to add support alternative language targets! 
Previously if you wanted to generate a Node snippet, you'd do:
```js
generateCodeSnippet(oas, operation, formData, authData, 'node', oasUrl);
```
This would generate you a `node-fetch` snippet and that's great but [HTTPSnippet](https://npm.im/@readme/httpsnippet) offers all sorts of other Node targets like `axios` or `request` that you couldn't use &mdash; with this change you can now do the following:
```js
generateCodeSnippet(oas, operation, formData, authData, ['node', 'axios'], oasUrl);
```
With the `language` argument as an array we'll now do a lookup in our supported targets for `node` and if `axios` is there we'll generate an Axios snippet!
I've mostly rewritten …
> feat: adding support to oas-to-snippet for alternative language targets

- example/src/Demo.jsx
- example/swagger-files/manual-api-doc-only.json
- packages/api-explorer/src/Doc.jsx
- packages/api-explorer/src/index.jsx
| --- |
https://explorer-pr-1262.herokuapp.com?selected=swagger-files%2Fmanual-api-doc-only.json
[demo]: https://explorer-pr-1262.herokuapp.com/
> fix: copy code buttons in markdown blocks

- packages/oas-to-snippet/__tests__/__snapshots__/index.test.js.snap
- packages/oas-to-snippet/__tests__/index.test.js
- packages/oas-to-snippet/src/supportedLanguages.js
> feat: exposing supported language target names in our export

- package-lock.json
- packages/oas-to-snippet/package-lock.json
- packages/oas-to-snippet/package.json
> feat: updating httpsnippet and httpsnippet-client-api

- packages/variable/index.jsx
| --- |
The SelectedAppContext provider needs to be re-exported from variable as the provider is now coming from readme and not the explorer - without the re-export it will always use SelectedAppContext's empty default state in the context consumer.
[Other half of this PR is in readme](https://github.com/readmeio/readme/pull/4616)
Requires a link to the changes in the api-explorer:
1. In the api-explorer, `cd packages/variable` and run `npm link`
2. Run `npm link @readme/variable` in `readme`
3. Run `npm run build` in the `api-explorer` before running start in readme
1. Create a new project with the subdomain 'developers' that is not an enterprise/enterprise child project
2. Create a new page in the guides section and add a code block to the page with the …
> fix: re-export SelectedAppContext

- packages/oas-extensions/__tests__/index.test.js
- packages/oas-extensions/index.js
> feat: adding an extension to control `api` simple mode

- packages/oas-to-har/__tests__/lib/configure-security.test.js
- packages/oas-to-har/src/lib/configure-security.js
> fix: stop adding `null` basic auth passwords into base64 encoded auth headers
