readmeio/api-explorer

packages/markdown/__tests__/__snapshots__/index.test.js.snap, packages/markdown/__tests__/index.test.js, packages/markdown/components/Heading.jsx
=> fix: TypeError: e.children[0].toLowerCase in Heading.jsx (#159)

example/src/Demo.jsx, package-lock.json, package.json, packages/api-explorer/package-lock.json, packages/api-logs/index.jsx, packages/api-logs/main.css, packages/api-logs/package-lock.json
I cleaned up a few things to match some designs that Maddie did!
=> Some css tweaks to fit maddie's designs

packages/api-explorer/__tests__/lib/oas-to-har.test.js, packages/api-explorer/__tests__/lib/parameters-to-json-schema.test.js, packages/api-explorer/src/lib/oas-to-har.js, packages/api-explorer/src/lib/parameters-to-json-schema.js
=> fix: allow to pass non-undefined values(#149)

packages/api-explorer/__tests__/lib/oas-to-har.test.js, packages/api-explorer/__tests__/lib/parameters-to-json-schema.test.js, packages/api-explorer/src/lib/oas-to-har.js, packages/api-explorer/src/lib/parameters-to-json-schema.js
Closes #149, #163
Also added support for falsy query and header values as well.
=> Nadalfederer 149 fix parameter bug

packages/api-explorer/api-explorer.css, packages/api-explorer/src/Doc.jsx, packages/api-explorer/src/ResponseSchema.jsx
Added sample responses! Needed to add a class to fix text color since the sidebar is dark.
=> Add sample responses to stripe style layout

packages/api-explorer/api-explorer.css, packages/api-explorer/src/ResponseSchemaBody.jsx
=> 💄 don't crop text and don't specify arbitrary max-height

packages/syntax-highlighter/codemirror.jsx, packages/syntax-highlighter/test/index.test.js
Asana Task: https://app.asana.com/0/681252538274980/1107660755900806/f
=> Add highlighting for Swift code samples

example/swagger-files/types.json, packages/api-explorer/__tests__/Params.test.jsx, packages/api-explorer/__tests__/fixtures/petstore/oas.json, packages/api-explorer/src/Params.jsx
=> add empty `properties` key to type 'object'

example/swagger-files/petstore.json, example/swagger-files/types.json, packages/api-explorer/__tests__/Params.test.jsx, packages/api-explorer/__tests__/fixtures/petstore/oas.json, packages/api-explorer/src/Params.jsx, packages/api-explorer/src/form-components/URLWidget.jsx
=> Add support for string format: url

example/bundle-hub2.css, packages/api-explorer/src/Example.jsx
Updates the styles on https://github.com/readmeio/api-explorer/pull/208 to match what we've got running in our production CSS.
https://readme.readme.io/css/bundle-hub2.css
=> Updating styles for multi-responses to match production.

packages/api-explorer/__tests__/lib/parameters-to-json-schema.test.js, packages/api-explorer/src/index.jsx, packages/api-explorer/src/lib/parameters-to-json-schema.js
=> Add support for common parameters

packages/api-explorer/style/main.scss
Move changes to a new branch from master, since the other one became merge hell
Other pr: https://github.com/readmeio/api-explorer/pull/207
=> Add css change from #207

packages/api-explorer/package-lock.json, packages/api-explorer/package.json
Check https://github.com/readmeio/oas/pull/75 for details.
=> Updating the oas dependency to resolve a bug in JSON Schema sorting

packages/api-explorer/src/AuthBox/style.scss
=> Fix AuthBox Dropdown

Procfile, package.json
|🧐 [API Explorer Review App](https://api-explorer-enhancemen-thtf9h.herokuapp.com/)|
|--|
Configure a Heroku review apps pipeline for the API Explorer.
=> Configure Heroku review apps pipeline.

README.md, packages/api-logs/README.md, packages/http-status-codes/.eslintignore, packages/http-status-codes/.eslintrc, packages/http-status-codes/.jsinspectrc, packages/http-status-codes/.npmignore, packages/http-status-codes/.prettierignore, packages/http-status-codes/.prettierrc, packages/http-status-codes/LICENSE, packages/http-status-codes/README.md, packages/http-status-codes/__tests__/.eslintrc, packages/http-status-codes/__tests__/index.test.js, packages/http-status-codes/jest.config.js, packages/http-status-codes/package-lock.json, packages/http-status-codes/package.json, packages/http-status-codes/src/index.js
This migrates our common [statuscodes.js](https://github.com/readmeio/api-explorer/blob/master/packages/api-explorer/src/lib/statuscodes.js) file over into a dedicated package.
=> feat: creating a new http-status-codes package

packages/api-explorer/package-lock.json, packages/api-explorer/package.json, packages/oas-to-har/package-lock.json, packages/oas-to-har/package.json
This updates `@readme/oas-tooling` to resolve a bug with how we'd convert parameters to JSON Schema in that if a parameter object had a `$ref` as one of its properties, we wouldn't fetch it.
- fix: if a ref is nested in a parameter object, fetch it [`#154`](https://github.com/readmeio/oas/pull/154)
=> chore(deps): upgrading @readme/oas-tooling to 3.1.8

packages/api-explorer/package-lock.json, packages/api-explorer/package.json, packages/oas-to-har/package-lock.json, packages/oas-to-har/package.json
Upgrading `@readme/oas-tooling` to resolve a bug where we'd sometimes remove descriptions from a schema property.
=> chore(deps): upgrading @readme/oas-tooling to 3.1.10

package-lock.json, packages/api-explorer/package-lock.json, packages/api-logs/package-lock.json, packages/markdown/package-lock.json
Reverts readmeio/api-explorer#634
Seeing weird stuff going on with `swagger2openapi`.
=> Revert "chore(deps-dev): Bump webpack from 4.42.0 to 4.43.0"

packages/markdown/components/Code/style.scss
=> style(markdown): pull CSS from readme

packages/api-explorer/package-lock.json, packages/api-explorer/package.json
- fix: bug where a string type would be added to anyOf, oneOf, and allOf [`#173`](https://github.com/readmeio/oas/pull/173)
=> chore(deps): upgrading @readme/oas-tooling to 3.3.4

packages/markdown/__tests__/__snapshots__/components.test.js.snap, packages/markdown/components/Callout/index.jsx
=> Fix RDMD callout titles... (AGAIN 🎩)

packages/markdown/components/Callout/style.scss
=> Add callout icon size and weight theme variables.

packages/markdown/components/Heading/style.scss, packages/markdown/package-lock.json, packages/markdown/package.json, packages/markdown/processor/plugin/section-anchor-id.js, packages/markdown/styles/gfm.scss
I forgot to invert the cascade between some base styles and a variable application for our markdown title sizes, which resulted in all headers being displayed at the same font size.
Will open a demo PR app in ReadMe when this is merged.
* I'm fixing a bug
=> Fix RDMD titles' font size issue.

.github/workflows/bundlewatch.yml, .github/workflows/ci.yml, package.json
Describe in detail what this PR is for.
=> ci: dinking around with bundlewatch

packages/syntax-highlighter/__tests__/__fixtures__/diff/index.js, packages/syntax-highlighter/__tests__/__fixtures__/diff/sample.diff, packages/syntax-highlighter/__tests__/__snapshots__/index.test.js.snap, packages/syntax-highlighter/codemirror.jsx, packages/syntax-highlighter/modes.js, packages/syntax-highlighter/uppercase.js
Adds support to `@readme/syntax-highlighter` for being able to highlight diffs.
=> feat: adding support for highlighting diffs

packages/api-explorer/package-lock.json, packages/api-explorer/package.json, packages/oas-to-har/package-lock.json, packages/oas-to-har/package.json, packages/oas-to-snippet/package-lock.json, packages/oas-to-snippet/package.json
Upgrades `@readme/oas-tooling` to v3.5.10 to resolve a bug where under certain condiitons we'd delete a `description` property off of a parameter.
See https://github.com/readmeio/oas/pull/260 for details.
=> chore(deps): upgrading @readme/oas-tooling to 3.5.10

package-lock.json, packages/api-explorer/package-lock.json, packages/api-explorer/package.json, packages/markdown-magic/package-lock.json, packages/oas-form/package-lock.json, packages/oas-to-har/package-lock.json, packages/oas-to-har/package.json, packages/oas-to-snippet/package-lock.json, packages/oas-to-snippet/package.json, packages/variable/package-lock.json
* feat: ship a compiled tooling lib dist (#302) ([3d9d6f5](https://github.com/readmeio/oas/commit/3d9d6f5)), closes [#302](https://github.com/readmeio/oas/issues/302)
=> chore(deps): upgrading oas to 5.2.0

example/index.html, example/src/ApiList.jsx, example/src/Demo.jsx, package-lock.json, package.json, packages/api-explorer/package-lock.json
> This is waiting on https://github.com/readmeio/ui/pull/462 to get a smaller size for our experiment toggles.
This gives a bit of a fresh coat of paint to the header on the dev server and https://preview.readme.io
=> style: incorporating ui components in the preview site

package-lock.json, package.json, packages/api-explorer/package-lock.json, packages/api-explorer/package.json, packages/api-explorer/src/Doc.jsx
=> fix: issues with the new json editor

package-lock.json, package.json, packages/api-explorer/package-lock.json, packages/api-explorer/package.json, packages/oas-to-har/package-lock.json, packages/oas-to-har/package.json, packages/oas-to-snippet/package-lock.json, packages/oas-to-snippet/package.json
This upgrades `oas` to 6.1.1 to resolve a regression in how [common parameters](https://swagger.io/docs/specification/describing-parameters/#common) were being included in JSON Schema for the form.
See https://github.com/readmeio/oas/pull/337 for details on the fix.
You can see this current lack of support for common parameters with our `common-parameters` example definition: https://preview.readme.io/?selected=swagger-files%2Fcommon-parameters.json
And locally with this fix:
=> fix: regression in support for common parameters

package-lock.json, package.json, packages/api-explorer/package-lock.json, packages/api-explorer/package.json, packages/oas-form/package-lock.json, packages/oas-form/package.json, packages/variable/package-lock.json, packages/variable/package.json
Reverts readmeio/api-explorer#1125
=> Revert "chore(deps-dev): bump webpack-cli from 3.3.12 to 4.3.0"

example/swagger-files/petstore.json, example/swagger-files/types.json, package-lock.json, package.json, packages/api-explorer/__tests__/Params.test.jsx, packages/api-explorer/package-lock.json, packages/api-explorer/package.json, packages/api-explorer/style/main.scss, packages/oas-form/__tests__/ArrayFieldTemplate_test.js, packages/oas-form/__tests__/ArrayField_test.js, packages/oas-form/__tests__/StringField_test.js, packages/oas-form/__tests__/anyOf_test.js, packages/oas-form/__tests__/uiSchema_test.js, packages/oas-form/src/components/fields/ArrayField.js, packages/oas-form/src/components/fields/StringField.js, packages/oas-form/src/components/widgets/BaseInput.js, packages/oas-form/src/types.js, packages/oas-to-har/package-lock.json, packages/oas-to-har/package.json, packages/oas-to-har/src/index.js, packages/oas-to-snippet/package-lock.json, packages/oas-to-snippet/package.json
Reverts readmeio/api-explorer#1155
=> Revert "feat: adding support for request examples"

example/swagger-files/types.json, packages/oas-to-har/__tests__/index.test.js
| --- |
This just tweaks types.json and adds a test to better account for the format:json work I did previously.
=> fix(oas-to-har): minor additions to the recent format:json fixes

packages/api-explorer/__tests__/__fixtures__/polymorphism/discriminators.json, packages/api-explorer/__tests__/form-components/MultiSchemaField.test.jsx, packages/api-explorer/src/form-components/MultiSchemaField.jsx
| --- |
This fixes a bug where `formData`, for some reason, becomes `undefined` and kills the explorer when it tries to set a `initialSelectedValue` with a discriminator propertyName.
I don't really understand what it is about this OAS that's causing it, but this PR fixes it. 🤷‍♂️ 
```json
{
"openapi": "3.0.1",
"info": {
"title": "Webhooks",
"version": "0.0.22"
},
"servers": [
{
"url": "https://httpbin.org"
}
],
"paths": {
"/webhooks": {
"post": {
"requestBody": {
"required": true,
"content": {
"application/json": {
"schema": {
"oneOf": [
{
"$ref": "#/components/schemas/ApplicationApprovedEvent"
},
{
"$ref": "#/components/schemas/ApplicationDeniedEvent"
}
],
"discriminator": {
"propertyName": "event_type",
"mapping": {
"application_approved": …
```
=> fix: bug where formData might be undefined with discrimators
